(function(){function h(a){throw a;}
var i=void 0,k=!0,m=null,t=!1,u,v=this,aa=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},w=function(a){return a!==i},x=function(a){return"array"==ba(a)},ca=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},y=function(a){return"string"==typeof a},da=function(a){return"number"==typeof a},ea=function(a){return"function"==ba(a)},fa=function(a){var b=typeof a;return"object"==b&&a!=m||"function"==b},ia=function(a){return a[ga]||
(a[ga]=++ha)},ga="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ha=0,ja=function(a,b,c){return a.call.apply(a.bind,arguments)},ka=function(a,b,c){a||h(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},A=function(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
ja:ka;return A.apply(m,arguments)},la=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},ma=Date.now||function(){return+new Date},B=function(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&w(b)?d[e]=b:d=d[e]?d[e]:d[e]={}},C=function(a,b){function c(){}c.prototype=b.prototype;a.g=b.prototype;a.prototype=new c;
a.prototype.constructor=a};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return A.apply(m,c)}return A(this,a)};var na=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a){if(!oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));return a},pa=/&/g,qa=/</g,ra=/>/g,sa=/\"/g,oa=/[&<>\"]/,ua=/&([^;\s<&]+);?/g;var D=Array.prototype,va=D.indexOf?function(a,b,c){return D.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},E=D.forEach?function(a,b,c){D.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wa=D.some?function(a,b,c){return D.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=y(a)?a.split(""):a,
f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return k;return t},xa=D.every?function(a,b,c){return D.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return t;return k},ya=function(a,b,c){a:{for(var d=a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a)){b=f;break a}b=-1}return 0>b?m:y(a)?a.charAt(b):a[b]},Aa=function(a){if(!x(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},Ba=function(a,b){var c=va(a,b);
0<=c&&D.splice.call(a,c,1)},Ca=function(a){return D.concat.apply(D,arguments)},Da=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ea=function(a,b,c){return 2>=arguments.length?D.slice.call(a,b):D.slice.call(a,b,c)};var F=function(a,b){this.x=w(a)?a:0;this.y=w(b)?b:0};F.prototype.u=function(){return new F(this.x,this.y)};var Fa=function(a,b){this.width=a;this.height=b};Fa.prototype.u=function(){return new Fa(this.width,this.height)};Fa.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};Fa.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Fa.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ga=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ha=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ia=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Ka=function(){var a=Ja,b;for(b in a)return t;return k},La="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),G=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<La.length;f++)c=La[f],Object.prototype.hasOwnProperty.call(d,
c)&&(a[c]=d[c])}};var Ma,Na,Oa,Pa,Qa,Ra=function(){return v.navigator?v.navigator.userAgent:m},Sa=function(){return v.navigator};Pa=Oa=Na=Ma=t;var Ta;if(Ta=Ra()){var Ua=Sa();Ma=0==Ta.indexOf("Opera");Na=!Ma&&-1!=Ta.indexOf("MSIE");Oa=!Ma&&-1!=Ta.indexOf("WebKit");Pa=!Ma&&!Oa&&"Gecko"==Ua.product}var Va=Ma,H=Na,I=Pa,J=Oa,Wa=Sa();Qa=-1!=(Wa&&Wa.platform||"").indexOf("Mac");var Xa=!!Sa()&&-1!=(Sa().appVersion||"").indexOf("X11"),Ya;
a:{var Za="",$a;if(Va&&v.opera)var ab=v.opera.version,Za="function"==typeof ab?ab():ab;else if(I?$a=/rv\:([^\);]+)(\)|;)/:H?$a=/MSIE\s+([^\);]+)(\)|;)/:J&&($a=/WebKit\/(\S+)/),$a)var bb=$a.exec(Ra()),Za=bb?bb[1]:"";if(H){var cb,db=v.document;cb=db?db.documentMode:i;if(cb>parseFloat(Za)){Ya=String(cb);break a}}Ya=Za}
var eb=Ya,fb={},K=function(a){var b;if(!(b=fb[a])){b=0;for(var c=na(String(eb)).split("."),d=na(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",j=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var q=l.exec(g)||["","",""],n=p.exec(j)||["","",""];if(0==q[0].length&&0==n[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==n[1].length?0:parseInt(n[1],10))?-1:(0==q[1].length?0:parseInt(q[1],10))>(0==n[1].length?0:parseInt(n[1],10))?1:
0)||((0==q[2].length)<(0==n[2].length)?-1:(0==q[2].length)>(0==n[2].length)?1:0)||(q[2]<n[2]?-1:q[2]>n[2]?1:0)}while(0==b)}b=fb[a]=0<=b}return b},gb={},hb=function(a){return gb[a]||(gb[a]=H&&!!document.documentMode&&document.documentMode>=a)};var ib,jb=!H||hb(9);!I&&!H||H&&hb(9)||I&&K("1.9.1");H&&K("9");var kb=function(a){a=a.className;return y(a)&&a.match(/\S+/g)||[]},lb=function(a,b){for(var c=kb(a),d=Ea(arguments,1),e=c.length+d.length,f=c,g=0;g<d.length;g++)0<=va(f,d[g])||f.push(d[g]);a.className=c.join(" ");return c.length==e};var N=function(a){return a?new mb(L(a)):ib||(ib=new mb)},ob=function(a,b){var c=b||document;c.querySelectorAll&&c.querySelector?c=c.querySelector("."+a):(c=b||document,c=(c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):nb(document,"*",a,b))[0]);return c||m},nb=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=
a.getElementsByClassName(c);if(b){for(var d={},e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&0<=va(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a},qb=function(a,b){Ga(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in pb?a.setAttribute(pb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,
b):a[d]=b})},pb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},rb=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new Fa(a.clientWidth,a.clientHeight)},O=function(a,b,c){return tb(document,arguments)},tb=function(a,b){var c=b[0],d=b[1];if(!jb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',
ta(d.name),'"');if(d.type){c.push(' type="',ta(d.type),'"');var e={};G(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(y(d)?c.className=d:x(d)?lb.apply(m,[c].concat(d)):qb(c,d));2<b.length&&ub(a,c,b,2);return c},ub=function(a,b,c,d){function e(c){c&&b.appendChild(y(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];if(ca(f)&&!(fa(f)&&0<f.nodeType)){var g=E,j;a:{if((j=f)&&"number"==typeof j.length){if(fa(j)){j="function"==typeof j.item||"string"==typeof j.item;break a}if(ea(j)){j=
"function"==typeof j.item;break a}}j=t}g(j?Da(f):f,e)}else e(f)}},vb=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},L=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},mb=function(a){this.c=a||v.document||document};u=mb.prototype;u.a=function(a){return y(a)?this.c.getElementById(a):a};u.Jb=function(a,b){return ob(a,b||this.c)};u.I=function(a,b,c){return tb(this.c,arguments)};u.createElement=function(a){return this.c.createElement(a)};u.createTextNode=function(a){return this.c.createTextNode(a)};
var P=function(a){return a.c.parentWindow||a.c.defaultView},wb=function(a){var b=a.c,a=!J&&"CSS1Compat"==b.compatMode?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new F(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)};mb.prototype.appendChild=function(a,b){a.appendChild(b)};mb.prototype.append=function(a,b){ub(L(a),a,arguments,1)};
mb.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var xb="StopIteration"in v?v.StopIteration:Error("StopIteration"),yb=function(){};yb.prototype.next=function(){h(xb)};yb.prototype.jc=function(){return this};var zb=function(a){if("function"==typeof a.B)return a.B();if(y(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ha(a)};var Ab=function(a,b){this.s={};this.n=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.ec(a)};u=Ab.prototype;u.f=0;u.tb=0;u.B=function(){Bb(this);for(var a=[],b=0;b<this.n.length;b++)a.push(this.s[this.n[b]]);return a};u.ka=function(){Bb(this);return this.n.concat()};u.$=function(a){return Cb(this.s,a)};
u.remove=function(a){return Cb(this.s,a)?(delete this.s[a],this.f--,this.tb++,this.n.length>2*this.f&&Bb(this),k):t};var Bb=function(a){if(a.f!=a.n.length){for(var b=0,c=0;b<a.n.length;){var d=a.n[b];Cb(a.s,d)&&(a.n[c++]=d);b++}a.n.length=c}if(a.f!=a.n.length){for(var e={},c=b=0;b<a.n.length;)d=a.n[b],Cb(e,d)||(a.n[c++]=d,e[d]=1),b++;a.n.length=c}};u=Ab.prototype;u.get=function(a,b){return Cb(this.s,a)?this.s[a]:b};u.set=function(a,b){Cb(this.s,a)||(this.f++,this.n.push(a),this.tb++);this.s[a]=b};
u.ec=function(a){var b;a instanceof Ab?(b=a.ka(),a=a.B()):(b=Ia(a),a=Ha(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};u.u=function(){return new Ab(this)};u.jc=function(a){Bb(this);var b=0,c=this.n,d=this.s,e=this.tb,f=this,g=new yb;g.next=function(){for(;;){e!=f.tb&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(xb);var g=c[b++];return a?g:d[g]}};return g};var Cb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Db=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Fb=function(a){if(Eb){Eb=t;var b=v.location;if(b){var c=b.href;if(c&&(c=(c=Fb(c)[3]||m)&&decodeURIComponent(c))&&c!=b.hostname)Eb=k,h(Error())}}return a.match(Db)},Eb=J;var Gb=function(a,b){var c;if(a instanceof Gb)this.z=w(b)?b:a.z,Hb(this,a.ya),c=a.sb,Ib(this),this.sb=c,c=a.Wa,Ib(this),this.Wa=c,Jb(this,a.rb),Kb(this,a.Wb),Lb(this,a.M.u()),c=a.qb,Ib(this),this.qb=c;else if(a&&(c=Fb(String(a)))){this.z=!!b;Hb(this,c[1]||"",k);var d=c[2]||"";Ib(this);this.sb=d?decodeURIComponent(d):"";d=c[3]||"";Ib(this);this.Wa=d?decodeURIComponent(d):"";Jb(this,c[4]);Kb(this,c[5]||"",k);Lb(this,c[6]||"",k);c=c[7]||"";Ib(this);this.qb=c?decodeURIComponent(c):""}else this.z=!!b,
this.M=new Mb(m,0,this.z)};u=Gb.prototype;u.ya="";u.sb="";u.Wa="";u.rb=m;u.Wb="";u.qb="";u.Xd=t;u.z=t;u.toString=function(){var a=[],b=this.ya;b&&a.push(Nb(b,Ob),":");if(b=this.Wa){a.push("//");var c=this.sb;c&&a.push(Nb(c,Ob),"@");a.push(encodeURIComponent(String(b)));b=this.rb;b!=m&&a.push(":",String(b))}if(b=this.Wb)this.Wa&&"/"!=b.charAt(0)&&a.push("/"),a.push(Nb(b,"/"==b.charAt(0)?Pb:Qb));(b=this.M.toString())&&a.push("?",b);(b=this.qb)&&a.push("#",Nb(b,Tb));return a.join("")};u.u=function(){return new Gb(this)};
var Hb=function(a,b,c){Ib(a);a.ya=c?b?decodeURIComponent(b):"":b;a.ya&&(a.ya=a.ya.replace(/:$/,""))},Jb=function(a,b){Ib(a);b?(b=Number(b),(isNaN(b)||0>b)&&h(Error("Bad port number "+b)),a.rb=b):a.rb=m},Kb=function(a,b,c){Ib(a);a.Wb=c?b?decodeURIComponent(b):"":b},Lb=function(a,b,c){Ib(a);b instanceof Mb?(a.M=b,a.M.hc(a.z)):(c||(b=Nb(b,Ub)),a.M=new Mb(b,0,a.z))},Wb=function(a,b,c){Ib(a);x(c)||(c=[String(c)]);Vb(a.M,b,c)},Ib=function(a){a.Xd&&h(Error("Tried to modify a read-only Uri"))};
Gb.prototype.hc=function(a){this.z=a;this.M&&this.M.hc(a);return this};
var Nb=function(a,b){return y(a)?encodeURI(a).replace(b,Xb):m},Xb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ob=/[#\/\?@]/g,Qb=/[\#\?:]/g,Pb=/[\#\?]/g,Ub=/[\#\?@]/g,Tb=/#/g,Yb=function(a){var b=window.location.href,a=Fb(a),b=Fb(b);return a[3]==b[3]&&a[4]==b[4]},Mb=function(a,b,c){this.A=a||m;this.z=!!c},$b=function(a){if(!a.m&&(a.m=new Ab,a.f=0,a.A))for(var b=a.A.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+
1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Zb(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};u=Mb.prototype;u.m=m;u.f=m;u.add=function(a,b){$b(this);this.A=m;var a=Zb(this,a),c=this.m.get(a);c||this.m.set(a,c=[]);c.push(b);this.f++;return this};u.remove=function(a){$b(this);a=Zb(this,a);return this.m.$(a)?(this.A=m,this.f-=this.m.get(a).length,this.m.remove(a)):t};u.$=function(a){$b(this);a=Zb(this,a);return this.m.$(a)};
u.ka=function(){$b(this);for(var a=this.m.B(),b=this.m.ka(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};u.B=function(a){$b(this);var b=[];if(a)this.$(a)&&(b=Ca(b,this.m.get(Zb(this,a))));else for(var a=this.m.B(),c=0;c<a.length;c++)b=Ca(b,a[c]);return b};u.set=function(a,b){$b(this);this.A=m;a=Zb(this,a);this.$(a)&&(this.f-=this.m.get(a).length);this.m.set(a,[b]);this.f++;return this};u.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};
var Vb=function(a,b,c){a.remove(b);0<c.length&&(a.A=m,a.m.set(Zb(a,b),Da(c)),a.f+=c.length)};Mb.prototype.toString=function(){if(this.A)return this.A;if(!this.m)return"";for(var a=[],b=this.m.ka(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.A=a.join("&")};Mb.prototype.u=function(){var a=new Mb;a.A=this.A;this.m&&(a.m=this.m.u(),a.f=this.f);return a};
var Zb=function(a,b){var c=String(b);a.z&&(c=c.toLowerCase());return c};
Mb.prototype.hc=function(a){if(a&&!this.z){$b(this);this.A=m;var b=this.m,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Vb(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ca(b)||y(b))E(b,c,this);else{var d;if("function"==typeof b.ka)d=b.ka();else if("function"!=typeof b.B)if(ca(b)||y(b)){d=[];for(var e=b.length,f=0;f<e;f++)d.push(f)}else d=Ia(b);else d=i;b=zb(b);e=b.length;for(f=0;f<e;f++)c.call(this,b[f],d&&d[f])}}this.z=a};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var ac=function(a,b){this.Sa=[];this.rd=b||m};u=ac.prototype;u.va=t;u.Ya=t;u.Za=0;u.Rc=t;u.ud=t;u.td=0;u.Jc=function(a,b){bc(this,a,b);this.Za--;0==this.Za&&this.va&&cc(this)};var bc=function(a,b,c){a.va=k;a.Zb=c;a.Ya=!b;cc(a)},dc=function(a){a.va&&(a.Rc||h(m),a.Rc=t)};ac.prototype.Hb=function(a){dc(this);bc(this,k,a)};
var ec=function(a){return wa(a.Sa,function(a){return ea(a[1])})},cc=function(a){a.$b&&(a.va&&ec(a))&&(v.clearTimeout(a.$b),delete a.$b);a.P&&(a.P.td--,delete a.P);for(var b=a.Zb,c=t,d=t;a.Sa.length&&0==a.Za;){var e=a.Sa.shift(),f=e[0],g=e[1],e=e[2];if(f=a.Ya?g:f)try{var j=f.call(e||a.rd,b);w(j)&&(a.Ya=a.Ya&&(j==b||j instanceof Error),a.Zb=b=j);b instanceof ac&&(d=k,a.Za++)}catch(l){b=l,a.Ya=k,ec(a)||(c=k)}}a.Zb=b;d&&a.Za&&(d=b,j=A(a.Jc,a,k),f=A(a.Jc,a,t),d.Sa.push([j,f,i]),d.va&&cc(d),b.ud=k);c&&
(a.$b=v.setTimeout(function(){h(b)},0))};var fc=function(a,b,c){c!=m&&v.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){vb(a)},0)};var gc=function(a,b){this.pd=new Gb(a);this.od=b?b:"callback";this.Xa=5E3},hc=0;
gc.prototype.send=function(a,b,c,d){var e=a||m,f=d||"_"+(hc++).toString(36)+ma().toString(36);v._callbacks_||(v._callbacks_={});a=this.pd.u();if(e)for(var g in e)(!e.hasOwnProperty||e.hasOwnProperty(g))&&Wb(a,g,e[g]);b&&(v._callbacks_[f]=function(a){ic(f,k);b.apply(i,arguments)},Wb(a,this.od,"_callbacks_."+f));var a=a.toString(),j={timeout:this.Xa,qd:k};g=j.document||document;var l=document.createElement("SCRIPT"),d={be:l,Xa:i},p=new ac(0,d),q=m,n=j.timeout!=m?j.timeout:5E3;0<n&&(q=window.setTimeout(function(){fc(l,
k);dc(p);bc(p,t,m)},n),d.Xa=q);l.onload=l.onreadystatechange=function(){if(!l.readyState||"loaded"==l.readyState||"complete"==l.readyState)fc(l,j.qd||t,q),p.Hb(m)};l.onerror=function(){fc(l,k,q);dc(p);bc(p,t,m)};qb(l,{type:"text/javascript",charset:"UTF-8",src:a});a=g.getElementsByTagName("HEAD");(!a||0==a.length?g.documentElement:a[0]).appendChild(l);p.Sa.push([m,function(){ic(f,t);c&&c(e)},i]);p.va&&cc(p);return{K:f,ae:p}};
var ic=function(a,b){v._callbacks_[a]&&(b?delete v._callbacks_[a]:v._callbacks_[a]=aa)};var jc=function(a){this.s=new Ab;a&&this.ec(a)},kc=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+ia(a):b.substr(0,1)+a};u=jc.prototype;u.add=function(a){this.s.set(kc(a),a)};u.ec=function(a){for(var a=zb(a),b=a.length,c=0;c<b;c++)this.add(a[c])};u.W=function(a){for(var a=zb(a),b=a.length,c=0;c<b;c++)this.remove(a[c])};u.remove=function(a){return this.s.remove(kc(a))};u.contains=function(a){return this.s.$(kc(a))};u.B=function(){return this.s.B()};u.u=function(){return new jc(this)};
u.jc=function(){return this.s.jc(t)};var mc=function(a,b){var c=[];c.push(a);c.push(b);return c.join("")};var nc=function(a,b){this.Ud=a;this.Sc=b},oc=k,pc=function(a,b){var c=[];c.push("[");for(var d=0;d<b.length;++d){var e=b[d];c.push("{actiontype:");c.push(e.Ud);e.Sc!=m&&(c.push(',actionvalue:"'),c.push(e.Sc),c.push('"'));c.push("},")}c.push("]");c=c.join("");d=[];oc?((new gc(a)).send({mtrcs:c}),d.push("Sent")):d.push("Metrics recording is turned off - would have sent");d.push(" mtrcs to ");d.push(a);d.push(": ");d.push(c);return c};B("hcm.MetricsData",nc);
B("hcm.setRecordMetricsEnabled",function(a){oc=a});B("hcm.getMetricsUrl",function(a,b,c){var d=[];d.push(mc(a,b));d.push("/api/metrics?");c&&(d.push("hl="),d.push(c));return d.join("")});B("hcm.recordMetrics",pc);B("hcm.trackConversion",function(a,b,c){var d=[];c&&(d.push(c.toString()),d.push(" | "));d.push(b);b=[];b.push(new nc("IP_CONVERSION_TRACKING",d.join("")));return pc(a,b)});var qc=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};qc.prototype.u=function(){return new qc(this.top,this.right,this.bottom,this.left)};qc.prototype.contains=function(a){return!this||!a?t:a instanceof qc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};var Q=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};Q.prototype.u=function(){return new Q(this.left,this.top,this.width,this.height)};
var rc=function(a){return new Q(a.left,a.top,a.right-a.left,a.bottom-a.top)},sc=function(a,b){return a==b?k:!a||!b?t:a.left==b.left&&a.width==b.width&&a.top==b.top&&a.height==b.height},tc=function(a,b){var c=Math.max(a.left+a.width,b.left+b.width),d=Math.max(a.top+a.height,b.top+b.height);a.left=Math.min(a.left,b.left);a.top=Math.min(a.top,b.top);a.width=c-a.left;a.height=d-a.top},uc=function(a,b){if(!a||!b)return m;var c=a.u();tc(c,b);return c};
Q.prototype.contains=function(a){return a instanceof Q?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};var wc=function(a,b,c){y(b)?vc(a,c,b):Ga(b,la(vc,a))},vc=function(a,b,c){a.style[String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})]=b},R=function(a,b){var c=L(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,m))?c[b]||c.getPropertyValue(b)||"":""},xc=function(a,b){return a.currentStyle?a.currentStyle[b]:m},Bc=function(a,b){return R(a,b)||xc(a,b)||a.style&&a.style[b]},Cc=function(a){return Bc(a,"position")},Ec=function(a,b,c){var d,e=
I&&(Qa||Xa)&&K("1.9");b instanceof F?(d=b.x,b=b.y):(d=b,b=c);a.style.left=Dc(d,e);a.style.top=Dc(b,e)},Fc=function(a){var b=a.getBoundingClientRect();H&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},Gc=function(a){if(H&&!hb(8))return a.offsetParent;for(var b=L(a),c=Bc(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Bc(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&
a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m},Jc=function(){for(var a=S.c.body,b=new qc(0,Infinity,Infinity,0),c=N(a),d=c.c.body,e=c.c.documentElement,f=!J&&"CSS1Compat"==c.c.compatMode?c.c.documentElement:c.c.body;a=Gc(a);)if((!H||0!=a.clientWidth)&&(!J||0!=a.clientHeight||a!=d)&&a!=d&&a!=e&&"visible"!=Bc(a,"overflow")){var g=Hc(a),j;j=a;if(I&&!K("1.9")){var l=parseFloat(R(j,"borderLeftWidth"));if(Ic(j))var p=
j.offsetWidth-j.clientWidth-l-parseFloat(R(j,"borderRightWidth")),l=l+p;j=new F(l,parseFloat(R(j,"borderTopWidth")))}else j=new F(j.clientLeft,j.clientTop);g.x+=j.x;g.y+=j.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=rb(P(c)||window);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=
b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:m},Hc=function(a){var b,c=L(a),d=Bc(a,"position"),e=I&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new F(0,0),g;b=c?L(c):document;if(g=H)if(g=!hb(9))g="CSS1Compat"!=N(b).c.compatMode;g=g?b.body:b.documentElement;if(a==g)return f;if(a.getBoundingClientRect)b=Fc(a),a=wb(N(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),
f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{e=a;do{f.x+=e.offsetLeft;f.y+=e.offsetTop;e!=a&&(f.x+=e.clientLeft||0,f.y+=e.clientTop||0);if(J&&"fixed"==Cc(e)){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}e=e.offsetParent}while(e&&e!=a);if(Va||J&&"absolute"==d)f.y-=c.body.offsetTop;for(e=a;(e=Gc(e))&&e!=c.body&&e!=g;)if(f.x-=e.scrollLeft,!Va||"TR"!=e.tagName)f.y-=e.scrollTop}return f},Lc=function(a,b,c){b instanceof Fa?(c=b.height,b=b.width):c==i&&h(Error("missing height argument"));a.style.width=
Dc(b,k);Kc(a,c)},Dc=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a},Kc=function(a,b){a.style.height=Dc(b,k)},T=function(a){if("none"!=Bc(a,"display"))return Mc(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Mc(a);b.display=c;b.position=e;b.visibility=d;return a},Mc=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=J&&!b&&!c;return(!w(b)||d)&&a.getBoundingClientRect?(a=Fc(a),new Fa(a.right-a.left,a.bottom-
a.top)):new Fa(b,c)},Nc=function(){var a=S.c.body,b=Hc(a),a=T(a);return new Q(b.x,b.y,a.width,a.height)},Oc=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")},U=function(a,b){a.style.display=b?"":"none"},Ic=function(a){return"rtl"==Bc(a,"direction")},Pc={thin:2,medium:4,thick:6},Qc=function(a,b){if("none"==xc(a,b+"Style"))return 0;var c=xc(a,b+"Width"),d;if(c in Pc)d=Pc[c];else if(/^\d+px?$/.test(c))d=
parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}return d},Rc=function(a){if(H){var b=Qc(a,"borderLeft"),c=Qc(a,"borderRight"),d=Qc(a,"borderTop"),a=Qc(a,"borderBottom");return new qc(d,c,a,b)}b=R(a,"borderLeftWidth");c=R(a,"borderRightWidth");d=R(a,"borderTopWidth");a=R(a,"borderBottomWidth");return new qc(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))},Sc=function(a){a.style[H?
"styleFloat":"cssFloat"]="left"},Tc=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;var Uc=function(){};Uc.prototype.Yb=t;Uc.prototype.j=function(){this.Yb||(this.Yb=k,this.i())};Uc.prototype.i=function(){this.Vd&&Vc.apply(m,this.Vd);if(this.Tc)for(;this.Tc.length;)this.Tc.shift()()};var Wc=function(a){a&&"function"==typeof a.j&&a.j()},Vc=function(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ca(d)?Vc.apply(m,d):Wc(d)}};var Xc=function(a){Xc[" "](a);return a};Xc[" "]=aa;var Yc=!H||hb(9),Zc=!H||hb(9),$c=H&&!K("9");!J||K("528");I&&K("1.9b")||H&&K("8")||Va&&K("9.5")||J&&K("528");I&&!K("8")||H&&K("9");var V=function(a,b){this.type=a;this.currentTarget=this.target=b};u=V.prototype;u.i=function(){};u.j=function(){};u.la=t;u.defaultPrevented=t;u.wb=k;u.stopPropagation=function(){this.la=k};u.preventDefault=function(){this.defaultPrevented=k;this.wb=t};var ad=function(a){a.preventDefault()};var bd=function(a,b){a&&this.init(a,b)};C(bd,V);var ed=[1,4,2];u=bd.prototype;u.target=m;u.relatedTarget=m;u.offsetX=0;u.offsetY=0;u.clientX=0;u.clientY=0;u.screenX=0;u.screenY=0;u.button=0;u.keyCode=0;u.charCode=0;u.ctrlKey=t;u.altKey=t;u.shiftKey=t;u.metaKey=t;u.Y=m;
u.init=function(a,b){var c=this.type=a.type;V.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(I){var e;a:{try{Xc(d.nodeName);e=k;break a}catch(f){}e=t}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=J||a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=J||a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Y=a;a.defaultPrevented&&this.preventDefault();delete this.la};u.stopPropagation=function(){bd.g.stopPropagation.call(this);this.Y.stopPropagation?this.Y.stopPropagation():this.Y.cancelBubble=k};
u.preventDefault=function(){bd.g.preventDefault.call(this);var a=this.Y;if(a.preventDefault)a.preventDefault();else if(a.returnValue=t,$c)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};u.Ca=function(){return this.Y};u.i=function(){};var fd=function(){},gd=0;u=fd.prototype;u.key=0;u.ga=t;u.gc=t;u.init=function(a,b,c,d,e,f){ea(a)?this.Nc=k:a&&a.handleEvent&&ea(a.handleEvent)?this.Nc=t:h(Error("Invalid listener argument"));this.xa=a;this.Ac=b;this.src=c;this.type=d;this.capture=!!e;this.mb=f;this.gc=t;this.key=++gd;this.ga=t};u.handleEvent=function(a){return this.Nc?this.xa.call(this.mb||this.src,a):this.xa.handleEvent.call(this.xa,a)};var hd={},id={},jd={},kd={},ld=function(a,b,c,d,e){if(b){if(x(b)){for(var f=0;f<b.length;f++)ld(a,b[f],c,d,e);return m}var d=!!d,g=id;b in g||(g[b]={f:0,C:0});g=g[b];d in g||(g[d]={f:0,C:0},g.f++);var g=g[d],j=ia(a),l;g.C++;if(g[j]){l=g[j];for(f=0;f<l.length;f++)if(g=l[f],g.xa==c&&g.mb==e){if(g.ga)break;return l[f].key}}else l=g[j]=[],g.f++;var p=md,q=Zc?function(a){return p.call(q.src,q.key,a)}:function(a){a=p.call(q.src,q.key,a);if(!a)return a},f=q;f.src=a;g=new fd;g.init(c,f,a,b,d,e);c=g.key;f.key=
c;l.push(g);hd[c]=g;jd[j]||(jd[j]=[]);jd[j].push(g);a.addEventListener?(a==v||!a.Bc)&&a.addEventListener(b,f,d):a.attachEvent(b in kd?kd[b]:kd[b]="on"+b,f);return c}h(Error("Invalid event type"))},nd=function(a,b,c,d,e){if(x(b))for(var f=0;f<b.length;f++)nd(a,b[f],c,d,e);else a=ld(a,b,c,d,e),hd[a].gc=k},od=function(a,b,c,d,e){if(x(b))for(var f=0;f<b.length;f++)od(a,b[f],c,d,e);else if(d=!!d,a=pd(a,b,d))for(f=0;f<a.length;f++)if(a[f].xa==c&&a[f].capture==d&&a[f].mb==e){qd(a[f].key);break}},qd=function(a){if(!hd[a])return t;
var b=hd[a];if(b.ga)return t;var c=b.src,d=b.type,e=b.Ac,f=b.capture;c.removeEventListener?(c==v||!c.Bc)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in kd?kd[d]:kd[d]="on"+d,e);c=ia(c);jd[c]&&(e=jd[c],Ba(e,b),0==e.length&&delete jd[c]);b.ga=k;if(b=id[d][f][c])b.Lc=k,rd(d,f,c,b);delete hd[a];return k},rd=function(a,b,c,d){if(!d.vb&&d.Lc){for(var e=0,f=0;e<d.length;e++)d[e].ga?d[e].Ac.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.Lc=t;0==f&&(delete id[a][b][c],id[a][b].f--,0==id[a][b].f&&
(delete id[a][b],id[a].f--),0==id[a].f&&delete id[a])}},sd=function(a){var b,c=0,d=b==m;b=!!b;if(a==m)Ga(jd,function(a){for(var e=a.length-1;0<=e;e--){var f=a[e];if(d||b==f.capture)qd(f.key),c++}});else if(a=ia(a),jd[a])for(var a=jd[a],e=a.length-1;0<=e;e--){var f=a[e];if(d||b==f.capture)qd(f.key),c++}},pd=function(a,b,c){var d=id;return b in d&&(d=d[b],c in d&&(d=d[c],a=ia(a),d[a]))?d[a]:m},ud=function(a,b,c,d,e){var f=1,b=ia(b);if(a[b]){a.C--;a=a[b];a.vb?a.vb++:a.vb=1;try{for(var g=a.length,j=0;j<
g;j++){var l=a[j];l&&!l.ga&&(f&=td(l,e)!==t)}}finally{a.vb--,rd(c,d,b,a)}}return Boolean(f)},td=function(a,b){a.gc&&qd(a.key);return a.handleEvent(b)},vd=function(a,b){var c=b.type||b,d=id;if(!(c in d))return k;if(y(b))b=new V(b,a);else if(b instanceof V)b.target=b.target||a;else{var e=b,b=new V(c,a);G(b,e)}var e=1,f,d=d[c],c=k in d,g;if(c){f=[];for(g=a;g;g=g.nb)f.push(g);g=d[k];g.C=g.f;for(var j=f.length-1;!b.la&&0<=j&&g.C;j--)b.currentTarget=f[j],e&=ud(g,f[j],b.type,k,b)&&b.wb!=t}if(t in d)if(g=
d[t],g.C=g.f,c)for(j=0;!b.la&&j<f.length&&g.C;j++)b.currentTarget=f[j],e&=ud(g,f[j],b.type,t,b)&&b.wb!=t;else for(d=a;!b.la&&d&&g.C;d=d.nb)b.currentTarget=d,e&=ud(g,d,b.type,t,b)&&b.wb!=t;return Boolean(e)},md=function(a,b){if(!hd[a])return k;var c=hd[a],d=c.type,e=id;if(!(d in e))return k;var e=e[d],f,g;if(!Zc){var j;if(!(j=b))a:{j=["window","event"];for(var l=v;f=j.shift();)if(l[f]!=m)l=l[f];else{j=m;break a}j=l}f=j;j=k in e;l=t in e;if(j){if(0>f.keyCode||f.returnValue!=i)return k;a:{var p=t;if(0==
f.keyCode)try{f.keyCode=-1;break a}catch(q){p=k}if(p||f.returnValue==i)f.returnValue=k}}p=new bd;p.init(f,this);f=k;try{if(j){for(var n=[],s=p.currentTarget;s;s=s.parentNode)n.push(s);g=e[k];g.C=g.f;for(var r=n.length-1;!p.la&&0<=r&&g.C;r--)p.currentTarget=n[r],f&=ud(g,n[r],d,k,p);if(l){g=e[t];g.C=g.f;for(r=0;!p.la&&r<n.length&&g.C;r++)p.currentTarget=n[r],f&=ud(g,n[r],d,t,p)}}else f=td(c,p)}finally{n&&(n.length=0)}return f}d=new bd(b,this);return f=td(c,d)},wd=0;var xd=function(a){this.Ra=a;this.n=[]};C(xd,Uc);var yd=[],W=function(a,b,c,d,e,f){x(c)||(yd[0]=c,c=yd);for(var g=0;g<c.length;g++){var j=ld(b,c[g],d||a,e||t,f||a.Ra||a);a.n.push(j)}},zd=function(a,b,c,d,e,f){if(x(c))for(var g=0;g<c.length;g++)zd(a,b,c[g],d,e,f);else{a:{d=d||a;f=f||a.Ra||a;e=!!e;if(b=pd(b,c,e))for(c=0;c<b.length;c++)if(!b[c].ga&&b[c].xa==d&&b[c].capture==e&&b[c].mb==f){b=b[c];break a}b=m}b&&(b=b.key,qd(b),Ba(a.n,b))}};xd.prototype.W=function(){E(this.n,qd);this.n.length=0};
xd.prototype.i=function(){xd.g.i.call(this);this.W()};xd.prototype.handleEvent=function(){h(Error("EventHandler.handleEvent not implemented"))};var Bd=RegExp("^(ar|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)","i"),Dd=function(){return Bd.test(Cd)};var Ed=function(){};C(Ed,Uc);u=Ed.prototype;u.Bc=k;u.nb=m;u.Pb=function(a){this.nb=a};u.addEventListener=function(a,b,c,d){ld(this,a,b,c,d)};u.removeEventListener=function(a,b,c,d){od(this,a,b,c,d)};u.dispatchEvent=function(a){return vd(this,a)};u.i=function(){Ed.g.i.call(this);sd(this);this.nb=m};var Fd=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}h(Error("Invalid JSON string: "+a))},Gd=function(a){return eval("("+a+")")},Jd=function(a){var b=[];Hd(new Id,a,b);return b.join("")},Id=function(){this.zb=i},Hd=function(a,b,c){switch(typeof b){case "string":Kd(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(x(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Hd(a,a.zb?a.zb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Kd(f,c),c.push(":"),Hd(a,a.zb?a.zb.call(b,f,e):e,c),d=","));c.push("}");
break;case "function":break;default:h(Error("Unknown type: "+typeof b))}},Ld={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Md=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,Kd=function(a,b){b.push('"',a.replace(Md,function(a){if(a in Ld)return Ld[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ld[a]=e+b.toString(16)}),'"')};var Nd=function(){};C(Nd,Ed);if(window.location&&(1==window.location.hash.indexOf("xdrp")||1==window.location.search.indexOf("xdrp")))H?document.execCommand("Stop"):I?window.stop():h(Error("stopped"));
var Od=function(a,b){return'<textarea name="'+a+'">'+(b&&(y(b)||b.constructor==String)?b.replace(/&/g,"&amp;"):b)+"</textarea>"},Pd=function(){if(I)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var c=a[b];if("stylesheet"==c.rel&&Yb(c.href)&&0>c.href.indexOf("?"))return c.href.split("#")[0]}a=document.getElementsByTagName("img");for(b=0;b<a.length;b++)if(c=a[b],Yb(c.src)&&0>c.src.indexOf("?"))return c.src.split("#")[0];if(H)return window.location.href.split("#")[0];b=window.location.href;
return b.substring(0,b.indexOf("/",b.indexOf("//")+2))+"/robots.txt"},Qd=0,Rd=function(a){var a=a.location.href,b=a.indexOf("?"),c=a.indexOf("#"),b=0>b?c:0>c?b:Math.min(b,c);return a.substring(b)};Nd.prototype.reset=function(){qd(this.Md);this.xb.parentNode.removeChild(this.xb);delete this.xb};var Sd=function(a,b){a!=m&&this.append.apply(this,arguments)};Sd.prototype.Ba="";Sd.prototype.set=function(a){this.Ba=""+a};Sd.prototype.append=function(a,b,c){this.Ba+=a;if(b!=m)for(var d=1;d<arguments.length;d++)this.Ba+=arguments[d];return this};Sd.prototype.toString=function(){return this.Ba};var Td=function(){return k};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Ud=function(a,b){var c=b||[];a&&c.push(a);return c},Vd=J&&"BackCompat"==document.compatMode,Wd=document.firstChild.children?"children":"childNodes",Xd=t,Yd=function(a){for(var a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ",b=function(b,c){return na(a.slice(b,c))},c=[],d=-1,e=-1,f=-1,g=-1,j=-1,l=-1,p=-1,q="",n="",s,r=0,lc=a.length,z=m,M=m,za=function(){0<=l&&(z.id=b(l,r).replace(/\\/g,""),l=-1);if(0<=p){var a=p==r?m:b(p,r);0>">~+".indexOf(a)?z.t=a:z.kb=a;p=-1}0<=j&&(z.S.push(b(j+1,r).replace(/\\/g,
"")),j=-1)};q=n,n=a.charAt(r),r<lc;r++)if("\\"!=q)if(z||(s=r,z={qa:m,ia:[],ob:[],S:[],t:m,kb:m,id:m,Nb:function(){return Xd?this.hd:this.t}},p=r),0<=d)if("]"==n){M.Qb?M.Rb=b(f||d+1,r):M.Qb=b(d+1,r);if((d=M.Rb)&&('"'==d.charAt(0)||"'"==d.charAt(0)))M.Rb=d.slice(1,-1);z.ob.push(M);M=m;d=f=-1}else"="==n&&(f=0<="|~^$*".indexOf(q)?q:"",M.type=f+n,M.Qb=b(d+1,r-f.length),f=r+1);else 0<=e?")"==n&&(0<=g&&(M.value=b(e+1,r)),g=e=-1):"#"==n?(za(),l=r+1):"."==n?(za(),j=r):":"==n?(za(),g=r):"["==n?(za(),d=r,M=
{}):"("==n?(0<=g&&(M={name:b(g+1,r),value:m},z.ia.push(M)),e=r):" "==n&&q!=n&&(za(),0<=g&&z.ia.push({name:b(g+1,r)}),z.pc=z.ia.length||z.ob.length||z.S.length,z.$d=z.qa=b(s,r),z.hd=z.t=z.kb?m:z.t||"*",z.t&&(z.t=z.t.toUpperCase()),c.length&&c[c.length-1].kb&&(z.oc=c.pop(),z.qa=z.oc.qa+" "+z.qa),c.push(z),z=m);return c},Zd=function(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},$d=function(a){return 1==a.nodeType},ae=function(a,b){return!a?"":"class"==
b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(Xd?a.getAttribute(b):a.getAttribute(b,2))||""},be={"*=":function(a,b){return function(c){return 0<=ae(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==ae(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+ae(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+ae(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=
" "+ae(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return ae(c,a)==b}}},ce="undefined"==typeof document.firstChild.nextElementSibling,de=!ce?"nextElementSibling":"nextSibling",ee=!ce?"previousElementSibling":"previousSibling",fe=ce?$d:Td,_lookLeft$$inline_311=function(a){for(;a=a[ee];)if(fe(a))return t;return k},_lookRight$$inline_312=function(a){for(;a=a[de];)if(fe(a))return t;return k},ge=function(a){var b=a.parentNode,c=0,d=b[Wd],e=a._i||-1,f=b._l||-1;if(!d)return-1;
d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[de])fe(b)&&(b._i=++c,a===b&&(e=c));return e},he=function(a){return!(ge(a)%2)},ie=function(a){return ge(a)%2},ke={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return _lookLeft$$inline_311},"last-child":function(){return _lookRight$$inline_312},"only-child":function(){return function(a){return!_lookLeft$$inline_311(a)||!_lookRight$$inline_312(a)?
t:k}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return t}return k}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=Yd(b)[0],d={ta:1};"*"!=c.t&&(d.t=1);c.S.length||(d.S=1);var e=je(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return ie;if("even"==b)return he;if(-1!=b.indexOf("n")){var c=
b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=ge(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var j=parseInt(b,10);return function(a){return ge(a)==j}}},le=H?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return Xd?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},
je=function(a,b){if(!a)return Td;var b=b||{},c=m;b.ta||(c=Zd(c,$d));b.t||"*"!=a.t&&(c=Zd(c,function(b){return b&&b.tagName==a.Nb()}));b.S||E(a.S,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Zd(c,function(a){return f.test(a.className)});c.count=b});b.ia||E(a.ia,function(a){var b=a.name;ke[b]&&(c=Zd(c,ke[b](b,a.value)))});b.ob||E(a.ob,function(a){var b,f=a.Qb;a.type&&be[a.type]?b=be[a.type](f,a.Rb):f.length&&(b=le(f));b&&(c=Zd(c,b))});b.id||a.id&&(c=Zd(c,function(b){return!!b&&b.id==a.id}));
c||"default"in b||(c=Td);return c},_childElements$$inline_321=function(a){a=a||Td;return function(b,c,d){for(var e=0,f=b[Wd];b=f[e++];)fe(b)&&((!d||_isUnique$$inline_333(b,d))&&a(b,e))&&c.push(b);return c}},_isDescendant$$inline_322=function(a,b){for(var c=a.parentNode;c&&c!=b;)c=c.parentNode;return!!c},_getElementsFuncCache$$inline_323={},me=function(a){var b=_getElementsFuncCache$$inline_323[a.qa];if(b)return b;var c=a.oc,c=c?c.kb:"",d=je(a,{ta:1}),e="*"==a.t,f=document.getElementsByClassName;if(c)if(f=
{ta:1},e&&(f.t=1),d=je(a,f),"+"==c)var g=d,b=function(a,b,c){for(;a=a[de];)if(!ce||$d(a)){(!c||_isUnique$$inline_333(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var j=d,b=function(a,b,c){for(a=a[de];a;){if(fe(a)){if(c&&!_isUnique$$inline_333(a,c))break;j(a)&&b.push(a)}a=a[de]}return b};else">"==c&&(b=_childElements$$inline_321(d));else if(a.id)d=!a.pc&&e?Td:je(a,{ta:1,id:1}),b=function(b,c){var e=N(b).a(a.id);if(e&&d(e)&&(9==b.nodeType||_isDescendant$$inline_322(e,b)))return Ud(e,c)};else if(f&&
/\{\s*\[native code\]\s*\}/.test(String(f))&&a.S.length&&!Vd)var d=je(a,{ta:1,S:1,id:1}),l=a.S.join(" "),b=function(a,b){for(var c=Ud(0,b),e,f=0,g=a.getElementsByClassName(l);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.pc?b=function(b,c){for(var d=Ud(0,c),e,f=0,g=b.getElementsByTagName(a.Nb());e=g[f++];)d.push(e);return d}:(d=je(a,{ta:1,t:1,id:1}),b=function(b,c){for(var e=Ud(0,c),f,g=0,j=b.getElementsByTagName(a.Nb());f=j[g++];)d(f,b)&&e.push(f);return e});return _getElementsFuncCache$$inline_323[a.qa]=
b},_queryFuncCacheDOM$$inline_326={},_queryFuncCacheQSA$$inline_327={},ne=function(a){var b=Yd(na(a));if(1==b.length){var c=me(b[0]);return function(a){if(a=c(a,[]))a.yb=k;return a}}return function(a){for(var a=Ud(a),c,f,g=b.length,j,l,p=0;p<g;p++){l=[];c=b[p];f=a.length-1;0<f&&(j={},l.yb=k);f=me(c);for(var q=0;c=a[q];q++)f(c,l,j);if(!l.length)break;a=l}return l}},oe=!!document.querySelectorAll&&(!J||K("526")),pe=function(a,b){if(oe){var c=_queryFuncCacheQSA$$inline_327[a];if(c&&!b)return c}if(c=
_queryFuncCacheDOM$$inline_326[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=k);if(oe&&!b&&-1==">~+".indexOf(c)&&(!H||-1==a.indexOf(":"))&&!(Vd&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return _queryFuncCacheQSA$$inline_327[a]=function(b){try{9==b.nodeType||d||h("");var c=b.querySelectorAll(e);H?c.Td=k:c.yb=k;return c}catch(f){return pe(a,k)(b)}}}var f=a.split(/\s*,\s*/);return _queryFuncCacheDOM$$inline_326[a]=
2>f.length?ne(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(ne(d)(a));return c}},_zipIdx$$inline_331=0,_nodeUID$$inline_332=H?function(a){return Xd?a.getAttribute("_uid")||a.setAttribute("_uid",++_zipIdx$$inline_331)||_zipIdx$$inline_331:a.uniqueID}:function(a){return a._uid||(a._uid=++_zipIdx$$inline_331)},_isUnique$$inline_333=function(a,b){if(!b)return 1;var c=_nodeUID$$inline_332(a);return!b[c]?b[c]=1:0},_zipIdxName$$inline_334="_zipIdx",_zip$$inline_335=function(a){if(a&&a.yb)return a;
var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;_zipIdx$$inline_331++;if(H&&Xd){var c=_zipIdx$$inline_331+"";a[0].setAttribute(_zipIdxName$$inline_334,c);for(var d=1,e;e=a[d];d++)a[d].getAttribute(_zipIdxName$$inline_334)!=c&&b.push(e),e.setAttribute(_zipIdxName$$inline_334,c)}else if(H&&a.Td)try{for(d=1;e=a[d];d++)$d(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0][_zipIdxName$$inline_334]=_zipIdx$$inline_331);for(d=1;e=a[d];d++)a[d][_zipIdxName$$inline_334]!=_zipIdx$$inline_331&&
b.push(e),e[_zipIdxName$$inline_334]=_zipIdx$$inline_331}return b},qe=function(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(b)&&(b=y(b)?document.getElementById(b):b,!b))return[];var b=b||document,c=b.ownerDocument||b.documentElement;Xd=b.contentType&&"application/xml"==b.contentType||Va&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(H?c.xml:b.xmlVersion||c.xmlVersion);return(c=pe(a)(b))&&c.yb?c:_zip$$inline_335(c)};qe.ia=ke;B("goog.dom.query",qe);
B("goog.dom.query.pseudos",qe.ia);var re=function(a){this.c=a},se=/\s*;\s*/;u=re.prototype;u.set=function(a,b,c,d,e,f){/[;=\s]/.test(a)&&h(Error('Invalid cookie name "'+a+'"'));/[;\r\n]/.test(b)&&h(Error('Invalid cookie value "'+b+'"'));w(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ma()+1E3*c)).toUTCString();this.c.cookie=a+"="+b+e+d+c+f};
u.get=function(a,b){for(var c=a+"=",d=(this.c.cookie||"").split(se),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};u.remove=function(a,b,c){var d=this.$(a);this.set(a,"",0,b,c);return d};u.ka=function(){return te(this).keys};u.B=function(){return te(this).wd};u.$=function(a){return w(this.get(a))};
var te=function(a){for(var a=(a.c.cookie||"").split(se),b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,wd:c}},ue=new re(document);ue.he=3950;var ve=[],we="/",xe="",ye=function(a){var b=[];b.push(a?"guide_debug.js":"guide_inproduct.js");a&&(b.push("?v="),b.push((new Date).getTime()));return b.join("")},ze=function(){var a=[];a.push("//ssl.gstatic.com/inproduct_help/guide/");a.push(ye());return a.join("")},Ae=function(a,b){var c=[];c.push(a);c.push("/support/gh/js/");c.push(ye(b));return c.join("")},Be=function(a,b,c,d,e,f,g,j){if(window.guidedhelp&&window.guidedhelp.loaded)j&&j();else{j&&ve.push(j);window.guidedhelp=window.guidedhelp||
{};window.guidedhelp.onLoad=function(){window.help.guide.setUseLocalDiskResources(f?!f:k);window.help.guide.init(a+b,c||"",d,g);for(var e=0;e<ve.length;e++)ve[e]();ve.length=0};var j=window.document,l=j.getElementsByTagName("head"),l=0<l.length?l[0]:j.body,j=j.createElement("script");j.setAttribute("type","text/javascript");j.setAttribute("src",f?Ae(a,e):ze());l.appendChild(j)}},Ce=function(){var a=ue.get("GuidedHelpResume");return a?Number(a.substring(0,a.indexOf(":"))):m},De=function(){var a=ue.get("GuidedHelpResume");
return a?a.substring(a.indexOf(":")+1):m},Ee=function(){ue.remove("GuidedHelpResume",we,xe)};B("hgb.loadFlow",function(a,b,c,d,e,f,g,j,l,p){Be(b,c,d,e,f,g,p,function(){window.help.guide.loadFlow(a,j,m,l)})});B("hgb.resumeCookiedFlow",function(a,b,c,d,e,f,g){var j=Ce();if(j){var l=De();Ee();Be(a,b,c,d,e,f,g,function(){window.help.guide.loadFlow(j,l,t)});return k}return t});B("hgb.setResumeCookieProperties",function(a,b){xe=a||"";we=b||""});
B("hgb.startFlowFromUrl",function(a,b,c,d,e,f,g){var j=N(g||window.top),j=P(j).location,j=j instanceof Gb?j.u():new Gb(j,i),l=j.M.get("ghstartflowid");if(l)try{var l=parseInt(l,10),p=j.M.get("ghstartstepid");Ee();Be(a,b,c,d,e,f,g,function(){window.help.guide.loadFlow(l,p)});return k}catch(q){}return t});var Ge=function(a,b){this.ja=a||1;this.Ta=b||Fe;this.ac=A(this.Hd,this);this.bc=ma()};C(Ge,Ed);Ge.prototype.enabled=t;var Fe=v.window;u=Ge.prototype;u.l=m;u.setInterval=function(a){this.ja=a;this.l&&this.enabled?(this.stop(),this.start()):this.l&&this.stop()};u.Hd=function(){if(this.enabled){var a=ma()-this.bc;0<a&&a<0.8*this.ja?this.l=this.Ta.setTimeout(this.ac,this.ja-a):(this.dispatchEvent("tick"),this.enabled&&(this.l=this.Ta.setTimeout(this.ac,this.ja),this.bc=ma()))}};
u.start=function(){this.enabled=k;this.l||(this.l=this.Ta.setTimeout(this.ac,this.ja),this.bc=ma())};u.stop=function(){this.enabled=t;this.l&&(this.Ta.clearTimeout(this.l),this.l=m)};u.i=function(){Ge.g.i.call(this);this.stop();delete this.Ta};var He=function(a,b,c){this.Sb=a;this.ja=b||0;this.Ra=c;this.Fd=A(this.Id,this)};C(He,Uc);u=He.prototype;u.K=0;u.i=function(){He.g.i.call(this);this.stop();delete this.Sb;delete this.Ra};u.start=function(a){this.stop();var b=this.Fd,a=w(a)?a:this.ja;ea(b)||(b&&"function"==typeof b.handleEvent?b=A(b.handleEvent,b):h(Error("Invalid listener argument")));this.K=2147483647<a?-1:Fe.setTimeout(b,a||0)};u.stop=function(){0!=this.K&&Fe.clearTimeout(this.K);this.K=0};u.Id=function(){this.K=0;this.Sb&&this.Sb.call(this.Ra)};var Ja={},Ie=m,Je=function(a){a=ia(a);delete Ja[a];Ka()&&Ie&&Ie.stop()},Le=function(){Ie||(Ie=new He(function(){var a=ma();Ga(Ja,function(c){Ke(c,a)});Ka()||Le()},20));var a=Ie;0!=a.K||a.start()};var Me=function(){this.G=0;this.Fc=this.startTime=m};C(Me,Ed);Me.prototype.Ua=function(){this.T("begin")};Me.prototype.pb=function(){this.T("end")};Me.prototype.T=function(a){this.dispatchEvent(a)};var Ne=function(a,b,c,d){Me.call(this);(!x(a)||!x(b))&&h(Error("Start and end parameters must be arrays"));a.length!=b.length&&h(Error("Start and end points must be the same length"));this.ha=a;this.Oc=b;this.duration=c;this.Pc=d;this.coords=[];this.da=t};C(Ne,Me);Ne.prototype.D=0;
Ne.prototype.play=function(a){if(a||0==this.G)this.D=0,this.coords=this.ha;else if(1==this.G)return t;Je(this);this.startTime=a=ma();-1==this.G&&(this.startTime-=this.duration*this.D);this.Fc=this.startTime+this.duration;this.D||this.Ua();this.T("play");-1==this.G&&this.T("resume");this.G=1;var b=ia(this);b in Ja||(Ja[b]=this);Le();Ke(this,a);return k};Ne.prototype.stop=function(a){Je(this);this.G=0;a&&(this.D=1);Oe(this,this.D);this.T("stop");this.pb()};
Ne.prototype.i=function(){0==this.G||this.stop(t);this.T("destroy");Ne.g.i.call(this)};var Ke=function(a,b){a.D=(b-a.startTime)/(a.Fc-a.startTime);1<=a.D&&(a.D=1);Oe(a,a.D);1==a.D?(a.G=0,Je(a),a.T("finish"),a.pb()):1==a.G&&a.Vb()},Oe=function(a,b){ea(a.Pc)&&(b=a.Pc(b));a.coords=Array(a.ha.length);for(var c=0;c<a.ha.length;c++)a.coords[c]=(a.Oc[c]-a.ha[c])*b+a.ha[c]};Ne.prototype.Vb=function(){this.T("animate")};Ne.prototype.T=function(a){this.dispatchEvent(new Pe(a,this))};
var Pe=function(a,b){V.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.duration=b.duration;this.D=b.D;this.state=b.G};C(Pe,V);var Qe=function(a){var b=a.offsetLeft,c=a.offsetParent;!c&&"fixed"==Cc(a)&&(c=L(a).documentElement);if(!c)return b;if(I)var d=Rc(c),b=b+d.left;else hb(8)&&(d=Rc(c),b-=d.left);return Ic(c)?c.clientWidth-(b+a.offsetWidth):b};var X=function(a,b,c,d,e){Ne.call(this,b,c,d,e);this.element=a};C(X,Ne);u=X.prototype;u.za=aa;u.Qc=function(){w(this.L)||(this.L=Ic(this.element));return this.L};u.Vb=function(){this.za();X.g.Vb.call(this)};u.pb=function(){this.za();X.g.pb.call(this)};u.Ua=function(){this.za();X.g.Ua.call(this)};var Re=function(a,b,c,d,e){(2!=b.length||2!=c.length)&&h(Error("Start and end points must be 2D"));X.apply(this,arguments)};C(Re,X);
Re.prototype.za=function(){var a=this.da&&this.Qc()?"right":"left";this.element.style[a]=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var Se=function(a,b,c,d){var e=[this.da?Qe(a):a.offsetLeft,a.offsetTop];Re.call(this,a,e,b,c,d)};C(Se,Re);Se.prototype.Ua=function(){this.ha=[this.da?Qe(this.element):this.element.offsetLeft,this.element.offsetTop];Se.g.Ua.call(this)};
var Te=function(a,b,c,d,e){(2!=b.length||2!=c.length)&&h(Error("Start and end points must be 2D"));X.apply(this,arguments)};C(Te,X);Te.prototype.za=function(){this.element.style.width=Math.round(this.coords[0])+"px";this.element.style.height=Math.round(this.coords[1])+"px"};var Ue=function(a,b,c,d,e){da(b)&&(b=[b]);da(c)&&(c=[c]);X.call(this,a,b,c,d,e);(1!=b.length||1!=c.length)&&h(Error("Start and end points must be 1D"))};C(Ue,X);Ue.prototype.za=function(){Oc(this.element,this.coords[0])};
var Ve=function(a,b,c){Ue.call(this,a,1,0,b,c)};C(Ve,Ue);var We=function(a,b,c){Ue.call(this,a,0,1,b,c)};C(We,Ue);var Xe=function(a){return 1-Math.pow(1-a,3)},Ye=function(a){return 3*a*a-2*a*a*a};var Ze=function(){var a=rb(P(S)||window),b=wb(S);return new Q(b.x,b.y,a.width,a.height)},$e=function(a){for(;a&&a.style;){if("none"==a.style.display)return t;a=a.parentNode}return k};B("help.guide.style.isElementVisible",$e);
var af=function(a){var b=P(S),c=new F(0,0),d=L(a)?L(a).parentWindow||L(a).defaultView:window,e=a;do{var f;if(d==b)f=Hc(e);else{f=e;var g=new F;if(1==f.nodeType){if(f.getBoundingClientRect){var j=Fc(f);g.x=j.left;g.y=j.top}else{var j=wb(N(f)),l=Hc(f);g.x=l.x-j.x;g.y=l.y-j.y}I&&!K(12)&&(j=i,j=i,H?j="-ms-transform":J?j="-webkit-transform":Va?j="-o-transform":I&&(j="-moz-transform"),l=i,j&&(l=Bc(f,j)),l||(l=Bc(f,"transform")),l?(f=l.match(Tc),j=!f?new F(0,0):new F(parseFloat(f[1]),parseFloat(f[2]))):
j=new F(0,0),g=new F(g.x+j.x,g.y+j.y))}else j=ea(f.Ca),l=f,f.targetTouches?l=f.targetTouches[0]:j&&f.Ca().targetTouches&&(l=f.Ca().targetTouches[0]),g.x=l.clientX,g.y=l.clientY;f=g}c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));a=T(a);return new Q(c.x,c.y,a.width,a.height)},df=function(a){var b,c=new Q(0,0,0,0);E(a,function(a){a=af(a);sc(a,c)||(b?tc(b,a):b=a)});if(b){for(var d,a=a[0],e=N(a).c.body;(a=bf(a))&&a!=e;)if((a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&
"visible"!=cf(a)){a:{d=b;var f=af(a),a=Math.max(d.left,f.left),e=Math.min(d.left+d.width,f.left+f.width);if(a<=e){var g=Math.max(d.top,f.top);d=Math.min(d.top+d.height,f.top+f.height);if(g<=d){d=new Q(a,g,e-a,d-g);break a}}d=m}break}d&&(b=d)}return b},cf=function(a){return R(a,"overflow")||xc(a,"overflow")||a.style.overflow},bf=function(a){for(var b=L(a),c=ef(a),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=ef(a),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>
a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return m},ef=function(a){return R(a,"position")||xc(a,"position")||a.style.position};var ff=function(a,b,c,d,e){X.apply(this,arguments);(2!=b.length||2!=c.length)&&h("[help.guide.anim.ScrollPage] Start and end points must be 2D");ld(this,["begin","animate","end"],this.Gd,t,this);nd(this,"finish",this.j,t,this)};C(ff,X);ff.prototype.Gd=function(a){P(S).scrollTo(a.x,a.y)};var gf=function(a,b,c,d){this.r=d||t;this.b=this.I();U(this.b,t);this.ca(a);b&&this.Cb(b);c&&this.Db(c);S.c.body.appendChild(this.b)};u=gf.prototype;u.e="left";u.Fa=0;u.Ga=0;u.Q=m;u.Va=m;u.wa=m;u.I=function(){return O("div",m)};u.a=function(){return this.b};u.j=function(){this.Q&&(this.Q.j(),delete this.Q);this.Va&&(this.Va.j(),delete this.Va);this.wa&&(this.wa.j(),delete this.wa);vb(this.b);delete this.b};
var hf=function(a){"opacity"in a.b.style&&!a.r?(a.wa=new Ve(a.b,500),nd(a.wa,"finish",a.j,t,a),a.wa.play()):a.j()};gf.prototype.Cb=function(a){a=a!=m?a:0;Dd()&&(a=-a);this.Fa=a};gf.prototype.Db=function(a){this.Ga=a!=m?a:0};gf.prototype.ca=function(a){a=a?a:"left";Dd()&&("left"==a?a="right":"right"==a&&(a="left"));this.e=a};
gf.prototype.Oa=function(){if("fixed"!=Cc(this.b)){var a=af(this.b),b=a.left,c=a.top;"left"==this.e?b+=20:"right"==this.e?b-=20:"up"==this.e?c+=20:"down"==this.e&&(c-=20);this.Q=new Re(this.b,[b,c],[a.left,a.top],500);this.Q.play()}};var jf=function(a){a.Va=new We(a.b,500);a.Va.play()};var kf=function(a,b,c,d,e){gf.call(this,a,b,c,e);d&&(this.Kb=d)};C(kf,gf);B("help.guide.Bracket",kf);kf.prototype.Kb=0;kf.prototype.ca=function(a){kf.g.ca.call(this,a);a=new Sd("iph-bracket-");a.append(this.e);this.b.className=a.toString()};
kf.prototype.na=function(a){ca(a)||(a=[a]);var b=df(a);if(b){var c=this.Fa-5,d=this.Ga-5;"up"==this.e||"down"==this.e?(this.b.style.width=Math.round(b.width+10+this.Kb)+"px",c+=b.left-3):(this.b.style.height=Math.round(b.height+10+this.Kb)+"px",d+=b.top-3);"up"==this.e?d+=b.top+b.height:"down"==this.e?d+=b.top-3:c="right"==this.e?c+(b.left-3):c+(b.left+b.width);Y.USE_SPOTLIGHT?(lf(k),b.left-=5,b.top-=5,b.width+=10,b.height+=10,mf(a[0],10,b)):(Ec(this.b,c,d),U(this.a(),k),"opacity"in this.b.style&&
!this.r&&(jf(this),this.Oa()))}else U(this.a(),t)};kf.prototype.decorate=kf.prototype.na;var nf=function(a,b,c){this.target=a;this.handle=b||a;this.Kc=c||new Q(NaN,NaN,NaN,NaN);this.c=L(a);this.J=new xd(this);ld(this.handle,["touchstart","mousedown"],this.wc,t,this)};C(nf,Ed);var of=H||I&&K("1.9.3");u=nf.prototype;u.clientX=0;u.clientY=0;u.screenX=0;u.screenY=0;u.sc=0;u.tc=0;u.ra=0;u.sa=0;u.qc=k;u.fa=t;u.rc=0;u.ad=t;u.da=t;u.X=function(){return this.J};
u.i=function(){nf.g.i.call(this);od(this.handle,["touchstart","mousedown"],this.wc,t,this);this.J.W();of&&this.c.releaseCapture();this.J=this.handle=this.target=m};var pf=function(a){w(a.L)||(a.L=Ic(a.target));return a.L};
nf.prototype.wc=function(a){var b="mousedown"==a.type;if(this.qc&&!this.fa&&(!b||(Yc?0==a.Y.button:"click"==a.type||a.Y.button&ed[0])&&(!J||!Qa||!a.ctrlKey))){qf(a);if(0==this.rc)if(this.dispatchEvent(new rf("start",this,a.clientX,a.clientY)))this.fa=k,a.preventDefault();else return;else a.preventDefault();var b=this.c,c=b.documentElement,d=!of;W(this.J,b,["touchmove","mousemove"],this.$c,d);W(this.J,b,["touchend","mouseup"],this.lb,d);of?(c.setCapture(t),W(this.J,c,"losecapture",this.lb)):W(this.J,
b?b.parentWindow||b.defaultView:window,"blur",this.lb);H&&this.ad&&W(this.J,b,"dragstart",ad);this.cd&&W(this.J,this.cd,"scroll",this.bd,d);this.clientX=this.sc=a.clientX;this.clientY=this.tc=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.ra=this.da?Qe(this.target):this.target.offsetLeft;this.sa=this.target.offsetTop;this.Ob=wb(N(this.c));ma()}else this.dispatchEvent("earlycancel")};
nf.prototype.lb=function(a){this.J.W();of&&this.c.releaseCapture();if(this.fa){qf(a);this.fa=t;var b=sf(this,this.ra),c=tf(this,this.sa);this.dispatchEvent(new rf("end",this,a.clientX,a.clientY,0,b,c))}else this.dispatchEvent("earlycancel");("touchend"==a.type||"touchcancel"==a.type)&&a.preventDefault()};var qf=function(a){var b=a.type;"touchstart"==b||"touchmove"==b?a.init(a.Ca().targetTouches[0],a.currentTarget):("touchend"==b||"touchcancel"==b)&&a.init(a.Ca().changedTouches[0],a.currentTarget)};
nf.prototype.$c=function(a){if(this.qc){qf(a);var b=(this.da&&pf(this)?-1:1)*(a.clientX-this.clientX),c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.fa){var d=this.sc-this.clientX,e=this.tc-this.clientY;if(d*d+e*e>this.rc)if(this.dispatchEvent(new rf("start",this,a.clientX,a.clientY)))this.fa=k;else{this.Yb||this.lb(a);return}}c=uf(this,b,c);b=c.x;c=c.y;this.fa&&this.dispatchEvent(new rf("beforedrag",this,a.clientX,a.clientY,
0,b,c))&&(vf(this,a,b,c),a.preventDefault())}};var uf=function(a,b,c){var d=wb(N(a.c)),b=b+(d.x-a.Ob.x),c=c+(d.y-a.Ob.y);a.Ob=d;a.ra+=b;a.sa+=c;b=sf(a,a.ra);a=tf(a,a.sa);return new F(b,a)};nf.prototype.bd=function(a){var b=uf(this,0,0);a.clientX=this.clientX;a.clientY=this.clientY;vf(this,a,b.x,b.y)};
var vf=function(a,b,c,d){a.da&&pf(a)?a.target.style.right=c+"px":a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new rf("drag",a,b.clientX,b.clientY,0,c,d))},sf=function(a,b){var c=a.Kc,d=!isNaN(c.left)?c.left:m,c=!isNaN(c.width)?c.width:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))},tf=function(a,b){var c=a.Kc,d=!isNaN(c.top)?c.top:m,c=!isNaN(c.height)?c.height:0;return Math.min(d!=m?d+c:Infinity,Math.max(d!=m?d:-Infinity,b))},rf=function(a,b,c,d,e,f,g){V.call(this,
a);this.clientX=c;this.clientY=d;this.left=w(f)?f:b.ra;this.top=w(g)?g:b.sa};C(rf,V);var wf=function(a,b,c){gf.call(this,m,m,m,b);c||(this.vc=new nf(this.b));a&&(this.o=O("iframe",{className:"iph-dialog-iframe",frameBorder:0,scrolling:"no",src:'javascript:""'}),U(this.o,t),document.body.appendChild(this.o),c||(this.uc=new nf(this.o,this.b)));this.Mb=t};C(wf,gf);u=wf.prototype;u.La="";u.V=0;u.Ha=m;u.o=m;
u.I=function(){this.Mc=O("a",{className:"iph-dialog-dismiss",href:"#__dismiss__",rel:"nextstep",innerHTML:"\u00d7"});this.Cd=O("div","iph-dialog-dismiss-container",this.Mc);this.gb=O("span","iph-dialog-title");this.Ka=O("span","iph-dialog-subtitle");this.Dd=O("div","iph-dialog-header",this.Ka,this.gb);this.Aa=O("div","iph-dialog-content");this.Z=O("div",m);var a=O("div",{id:"inproduct-guide-modal",className:"iph-dialog"},this.Cd,this.Dd,this.Aa,this.Z);Dd()&&(a.setAttribute("dir","rtl"),wc(a,{"text-align":"right"}),
Sc(this.Mc),Sc(this.Ka));return a};u.lc=function(){return this.Aa};u.j=function(){this.o&&(this.uc&&this.uc.j(),vb(this.o),delete this.o);this.vc&&this.vc.j();wf.g.j.call(this)};u.F=function(a){U(this.a(),a);this.o?U(this.o,a):a&&("opacity"in this.a().style&&!this.r)&&jf(this);a||(this.Mb=t)};
var xf=function(a){return ob("iph-resize",a.Aa)||a.Aa},yf=function(a,b){var c,d;if(Y.ANIMATE_SIZE&&(c=xf(a)))d=T(c),Kc(c,"auto");a.Aa.innerHTML=b;c=xf(a);if(!c||!a.Mb||!Y.ANIMATE_SIZE)a.Mb=k,U(a.Aa,!/^[\s\xa0]*$/.test(b));else{var e=O("div","iph-resize-inner");e.innerHTML=c.innerHTML;c.innerHTML="";c.appendChild(e);wc(c,"overflow","none");var f=T(c);Lc(e,f.width,f.height);d=new Te(c,[d.width,d.height],[f.width,f.height],500,Ye);d.play();nd(d,"end",function(){Kc(c,"auto");Kc(e,"auto")})}};
wf.prototype.ca=function(a){a=a||"left";Dd()&&("left"==a?a="right":"right"==a&&(a="left"));this.e=a;this.Ha&&zf(this,this.Ha)};wf.prototype.Cb=function(a){a=a!=m?a:0;Dd()&&(a=-a);this.Fa=a};wf.prototype.Db=function(a){this.Ga=a!=m?a:0};
var zf=function(a,b){a.Ha=b;a.Z.className="iph-dialog-pointer";if(b){a.Z.className+="-"+a.e;var c=b.leftOffset||0,d=b.topOffset||0;Dd()&&(c=-c);var e=T(a.b);if("left"==a.e||"right"==a.e)d+=Math.round(e.height/2),d=Math.max(d,16),d=Math.min(d,e.height-16),a.Z.style.top=d+"px",a.Z.style.left="";else if("up"==a.e||"down"==a.e)c+=Math.round(e.width/2),c=Math.max(c,16),c=Math.min(c,e.width-16),a.Z.style.left=c+"px",a.Z.style.top=""}};wf.prototype.Eb=function(a){this.V=a?4:0};var Af=function(a,b){wf.call(this,a,b,k);a&&lb(this.o,"iph-butterbar-iframe");lb(this.a(),"iph-butterbar");this.a().setAttribute("id","inproduct-guide-butterbar");U(this.a(),t)};C(Af,wf);Af.prototype.F=function(a){if(this.o){if(a){var b=T(this.a());Lc(this.o,b.width-2,b.height-2)}U(this.a(),a);U(this.o,a)}else b="none"!=this.a().style.display,a&&!b&&!this.r?this.Oa(k):!a&&b&&!this.r?this.Oa(t):U(this.a(),a)};
Af.prototype.Oa=function(a){var b=Ze(),c=af(this.a()),b=Math.round(b.width/2);a?(U(this.a(),k),this.Q=new Re(this.a(),[b,-c.height],[b,0],500)):(this.Q=new Re(this.a(),[b,0],[b,-c.height],500),nd(this.Q,"finish",this.nd,t,this));this.Q.play()};Af.prototype.nd=function(){U(this.a(),t)};var Bf=function(a,b,c,d,e,f){this.ic=a;this.content=b;this.Jd=c||[];this.Nd=d||[];this.Ld=e||t;this.Kd=f||{}};Bf.prototype.toString=function(){var a=[];a.push("Flow([");a.push(String(this.ic));a.push("], ");a.push(String(this.content));a.push(", [");a.push(String(this.Jd));a.push("], [");a.push(String(this.Nd));a.push("], ");a.push(this.Ld);a.push(", {");var b=[];Ga(this.Kd,function(a,d){b.push('"'+a+'": '+!!d)});a.push(b.join(", "));a.push("})");return a.join("")};
var Kf=function(a){if(a){G(a,Bf.prototype);a.steps&&E(a.steps,function(a){G(a,Cf.prototype);a.pointers&&E(a.pointers,function(a){G(a,Df.prototype)});a.brackets&&E(a.brackets,function(a){G(a,Ef.prototype)});a.transitions&&E(a.transitions,function(a){Ff(a)})});if(a.content){var b=a.content;G(b,Gf.prototype);b.steps&&E(b.steps,function(a){G(a,Hf.prototype);a.pointers&&E(a.pointers,function(a){G(a,If.prototype)})})}a.transitionGroups&&Ga(a.transitionGroups,function(a){G(a,Jf.prototype);a.transitions&&
E(a.transitions,function(a){Ff(a)})})}},Gf=function(a,b,c){this.name=a;this.ic=b;this.ma=c||""};Gf.prototype.toString=function(){var a=[];a.push('Content("');a.push(this.name);a.push('", [');a.push(String(this.ic));a.push('], "');a.push(this.ma);a.push('")');return a.join("")};var Cf=function(a,b,c,d,e,f,g,j,l,p,q,n){this.id=a;this.dc=b||[];this.xd=c||[];this.fc=d||[];this.zd=e||t;this.position=f||"";this.$a=g||0;this.ab=j||0;this.width=l||400;this.direction=p||"left";this.Ad=q||[];this.yd=n||t};
Cf.prototype.toString=function(){var a=[];a.push('Step("');a.push(this.id);a.push('", [');a.push(String(this.dc));a.push("], [");a.push(String(this.xd));a.push("], [");a.push(String(this.fc));a.push("], ");a.push(this.zd);a.push(', "');a.push(this.position);a.push('", ');a.push(this.$a);a.push(", ");a.push(this.ab);a.push(', "');a.push(this.width);a.push(', "');a.push(this.direction);a.push('", [');a.push(String(this.Ad));a.push("], ");a.push(this.yd);a.push(")");return a.join("")};
var Hf=function(a,b,c,d,e,f){this.id=a;this.content=b;this.title=c||"";this.Sd=d||"";this.dc=e||[];this.Rd=f||""};Hf.prototype.toString=function(){var a=[];a.push('StepContent("');a.push(this.id);a.push('", "');a.push(this.content);a.push('", "');a.push(this.title);a.push('", "');a.push(this.Sd);a.push('", [');a.push(String(this.dc));a.push('], "');a.push(this.Rd);a.push('")');return a.join("")};var Jf=function(a,b){this.id=a;this.fc=b};
Jf.prototype.toString=function(){var a=[];a.push('TransitionGroup("');a.push(this.id);a.push('", [');a.push(String(this.fc));a.push("])");return a.join("")};var Of=function(a,b,c){this.step=a;this.Yd=b;this.group=c||""};Of.prototype.toString=function(){var a=[];a.push('Transition("');a.push(this.step);a.push('", [');a.push(String(this.Yd));a.push('], "');a.push(this.group);a.push('")');return a.join("")};
var Ff=function(a){G(a,Of.prototype);a.on&&E(a.on,function(a){G(a,Pf.prototype)})},Pf=function(a,b,c){this.type=a;this.Zd=b;this.value=c||""};Pf.prototype.toString=function(){var a=[];a.push('Condition("');a.push(this.type);a.push('", "');a.push(this.Zd);a.push('", "');a.push(this.value);a.push('")');return a.join("")};var Df=function(a,b,c,d,e){this.id=a;this.position=b||"";this.$a=c||0;this.ab=d||0;this.direction=e||"left"};
Df.prototype.toString=function(){var a=[];a.push("Pointer(");a.push(this.id);a.push(', "');a.push(this.position);a.push('", ');a.push(this.$a);a.push(", ");a.push(this.ab);a.push(', "');a.push(this.direction);a.push('")');return a.join("")};var If=function(a,b){this.id=a;this.caption=b};If.prototype.toString=function(){var a=[];a.push("PointerContent(");a.push(this.id);a.push(', "');a.push(this.caption);a.push('")');return a.join("")};
var Ef=function(a,b,c,d,e){this.elements=a;this.$a=b||0;this.ab=c||0;this.Qd=d||0;this.direction=e||"left"};Ef.prototype.toString=function(){var a=[];a.push("Bracket([");a.push(String(this.elements));a.push("], ");a.push(this.$a);a.push(", ");a.push(this.ab);a.push(", ");a.push(this.Qd);a.push(', "');a.push(this.direction);a.push('")');return a.join("")};var Qf={ce:"change",de:"click",ee:"focusIn",fe:"focusOut",ge:"keyPress",ie:"mouseOut",je:"mouseOver",ke:"submit",le:"touchEnd"};var Rf=function(a){V.call(this,"newflowlink");this.Wd=a};C(Rf,V);var Sf=function(a,b){V.call(this,"guide_transition");this.Bd=a;this.Ed=b};C(Sf,V);var Z=function(a,b,c,d,e,f){gf.call(this,b,c,d,f);this.Qa.innerHTML=a||"";this.Eb(e);this.r||nd(this.b,"click",this.xc,k,this)};C(Z,gf);B("help.guide.Pointer",Z);Z.prototype.ua=m;Z.prototype.I=function(){this.zc=O("div");this.Qa=O("div");this.yc=O("div");var a=O("div","iph-pointer",this.zc,this.Qa,this.yc);Dd()&&(this.Qa.setAttribute("dir","rtl"),wc(this.Qa,{"text-align":"right"}));return a};Z.prototype.j=function(){this.ua&&(this.ua.j(),delete this.ua);Z.g.j.call(this)};Z.prototype.dispose=Z.prototype.j;
Z.prototype.Eb=function(a){this.V=a?10:0};Z.prototype.ca=function(a){Z.g.ca.call(this,a);var a=new Sd("iph-pointer-head-"),b=new Sd("iph-pointer-caption-"),c=new Sd("iph-pointer-end-");a.append(this.e);b.append(this.e);c.append(this.e);this.zc.className=a.toString();this.Qa.className=b.toString();this.yc.className=c.toString()};
Z.prototype.na=function(a){var b=this.Fa,c=this.Ga;if(a){ca(a)||(a=[a]);a=df(a);if(!a){U(this.a(),t);return}var d=T(this.b);"left"==this.e?(b+=a.left+a.width+this.V,c+=a.top+Math.ceil(a.height/2)-Math.floor(d.height/2)):"right"==this.e?(b+=a.left-d.width-this.V,c+=a.top+Math.ceil(a.height/2)-Math.floor(d.height/2)):"up"==this.e?(b+=a.left+Math.ceil(a.width/2)-Math.floor(d.width/2),c+=a.top+a.height+13+this.V):"down"==this.e&&(b+=a.left+Math.ceil(a.width/2)-Math.floor(d.width/2),c+=a.top-d.height-
13-this.V)}Ec(this.b,b,c);Tf(this)};Z.prototype.decorate=Z.prototype.na;var Tf=function(a){U(a.a(),k);"opacity"in a.b.style&&!a.r&&(jf(a),a.Oa())};Z.prototype.xc=function(a){a.stopPropagation();a.preventDefault();Uf(this,0)};
var Uf=function(a,b){if("fixed"!=Cc(a.b)){var c=af(a.b),d=c.left,c=c.top;"left"==a.e?d-=Vf(b):"right"==a.e?d+=Vf(b):"up"==a.e?c-=Vf(b):"down"==a.e&&(c+=Vf(b));var e=[d,c];a.ua=new Se(a.b,e,150);nd(a.ua,"finish",function(){var a=b;Ec(this.b,e[0],e[1]);5>a?(++a,Uf(this,a)):nd(this.b,"click",this.xc,k,this)},t,a);a.ua.play()}},Vf=function(a){switch(a){case 0:return 10;case 1:return-10;case 2:return 6;case 3:return-6;case 4:return 3;case 5:return-3;default:return 0}};var Wf=function(a){this.b=a;a=H?"focusout":"blur";this.fd=ld(this.b,H?"focusin":"focus",this,!H);this.gd=ld(this.b,a,this,!H)};C(Wf,Ed);Wf.prototype.handleEvent=function(a){var b=new bd(a.Ca());b.type="focusin"==a.type||"focus"==a.type?"focusin":"focusout";this.dispatchEvent(b)};Wf.prototype.i=function(){Wf.g.i.call(this);qd(this.fd);qd(this.gd);delete this.b};var Xf=function(){this.jb=[];this.h=new xd(this);this.l=new Ge(250);this.Ib=[];this.Lb=[]};C(Xf,Ed);Xf.prototype.pa=m;Xf.prototype.Pa=t;Xf.prototype.i=function(){Xf.g.i.call(this);Yf(this);Zf(this);this.h.j();this.l.j()};var Yf=function(a){for(;0<a.Ib.length;)a.Ib.pop().j()},Zf=function(a){for(;0<a.Lb.length;){var b=a.Lb.pop();b.element.detachEvent&&b.element.detachEvent(b.type,b.Hb)}};Xf.prototype.R=function(a){$f(this,a)};Xf.prototype.Bb=function(){$f(this)};
Xf.prototype.stop=function(){Zf(this);this.h.W();this.Pa=k;this.pa=m;this.jb=[]};
var $f=function(a,b){if(!a.Pa&&a.pa){var c=ag(a,b);c&&vd(a,new Sf(a.pa,c))}},ag=function(a,b){if(!a.Pa&&a.pa){var c,d=new jc,e=new jc;b&&d.add(b);if((c=ya(a.jb,function(a){return xa(a.on,function(a){if(d.contains(a))return k;if(e.contains(a))return t;try{var b;var c=a.selector,f=a.type,q=a.value;if("url"==f||"notUrl"==f)b=Boolean(P(S).location.href.match(c))==("url"==f);else{var n;c&&(n=bg(c));var s=Boolean(n)&&0<n.length;b="visible"==f||"notVisible"==f?(s&&$e(n[0]))==("visible"==f):"enabled"==f||
"disabled"==f?(s&&!n[0].disabled)==("enabled"==f):"checked"==f||"notChecked"==f?(s&&n[0].checked)==("checked"==f):"hasChildren"==f||"noChildren"==f?(s&&n[0].hasChildNodes())==("hasChildren"==f):"equals"==f||"notEquals"==f?(s&&(n[0].value==q||n[0].innerHTML==q||n[0].options!=m&&n[0].options[n[0].selectedIndex].value==q))==("equals"==f):"regExp"==f||"notRegExp"==f?(s&&(Boolean(n[0].value.match(q))||Boolean(n[0].innerHTML.match(q))))==("regExp"==f):"lessThan"==f?s&&n[0].value!=m&&""!=n[0].value&&Number(n[0].value)<
Number(q):"greaterThan"==f?s&&n[0].value!=m&&""!=n[0].value&&Number(n[0].value)>Number(q):"lessOrEqual"==f?s&&n[0].value!=m&&""!=n[0].value&&Number(n[0].value)<=Number(q):"greaterOrEqual"==f?s&&n[0].value!=m&&""!=n[0].value&&Number(n[0].value)>=Number(q):t}}catch(r){b=t}(b?d:e).add(a);return b},this)},a))&&c.step!=a.pa)return a.Pa=k,c.step}return m};var cg=function(a,b,c,d,e,f){this.w=b;this.N=c||m;this.r=e||t;this.product=f;this.aa=d||new Xf;d&&(this.Wc=k);this.q=new Af(this.w.iframe,this.r);this.k=new wf(this.w.iframe,this.r);this.Ja=[];this.Ia=[];this.Ea=m;this.cb=t;this.v=[];this.ba=[];this.Da=this.d=m;this.bb=[];this.Fb=this.Ab=t;this.Gb=rb(P(S)||window);this.l=new Ge(250);this.h=new xd(this);W(this.h,this.q.a(),"click",this.eb,k);W(this.h,this.q.a(),["mouseover","mouseout"],this.fb,k);W(this.h,this.k.a(),"click",this.eb,k);W(this.h,this.k.a(),
["mouseover","mouseout"],this.fb,k);W(this.h,this.aa,"guide_transition",this.Zc);W(this.h,P(S),"resize",this.Yc);W(this.h,P(S),"beforeunload",this.Xc);W(this.h,this.l,"tick",this.Bb)};C(cg,Ed);u=cg.prototype;u.eb=function(a){var b=a.target,c=b.getAttribute("rel");!c&&b.parentNode&&(b=b.parentNode,c=b.getAttribute("rel"));if("nextstep"==c||"newflow"==c)if(a.stopPropagation(),a.preventDefault(),(a=b.hash)&&0==a.lastIndexOf("#",0))a=a.substr(1),"nextstep"==c?dg(this,a):this.dispatchEvent(new Rf(a))};
u.fb=function(a){"A"==a.target.tagName&&(a.stopPropagation(),a.preventDefault(),"mouseover"==a.type?this.aa.stop():eg(this))};u.Yc=function(){var a=rb(P(S)||window);if(this.Gb.width!=a.width||this.Gb.height!=a.height)this.Gb=a,(a=ag(this.aa))?dg(this,a):(this.q&&(this.q.a()&&"mobile"!=this.product&&(this.q.a().style.left="50%"),this.q.o&&"mobile"!=this.product&&(this.q.o.style.left="50%")),fg(this))};
u.Bb=function(){this.l.stop();for(var a=t,b=0;b<this.v.length;++b){var c=af(this.v[b]);!sc(c,this.ba[b])&&1!=Math.abs(c.top-this.ba[b].top)&&(this.ba[b]=c,a=k)}a&&(gg(this),hg(this,k),ig(this),jg(this,k),fg(this,k));if(this.cb&&(a=kg(this)))a=af(a),b=Ze(),a.top+a.height>=b.top&&a.top<=b.top+b.height&&lg(this);this.l.start()};
u.Xc=function(){if(this.N!=m){var a=(this.d?this.d.id:m)||"";ue.set("GuidedHelpResume",this.N+":"+(a?a:""),120,we,xe);a=[];this.Ab&&a.push(new nc("IP_GH_COMPLETED",this.N.toString()));this.Fb&&a.push(new nc("IP_GH_ERROR",this.N.toString()));a.push(mg(this));pc(ng(),a)}};u.i=function(){cg.g.i.call(this);og();Wc(this.h);Wc(this.l);this.Wc||Wc(this.aa);Wc(this.q);Wc(this.k);gg(this);ig(this)};
u.ma=function(){this.l.stop();this.aa.stop();Aa(this.v);Aa(this.ba);this.q.F(t);this.k.F(t);gg(this);ig(this);lg(this);this.Da=this.d=m;this.dispatchEvent("dismiss");if(window.guidedhelp&&window.guidedhelp.onFlowDismiss)window.guidedhelp.onFlowDismiss();if(window.guidedhelp&&window.guidedhelp.onFlowStepSet)window.guidedhelp.onFlowStepSet("__dismiss__");if(this.N!=m){var a=[];a.push(new nc("IP_GH_DISMISSED",this.N.toString()));this.Ab&&a.push(new nc("IP_GH_COMPLETED",this.N.toString()));this.Fb&&a.push(new nc("IP_GH_ERROR",
this.N.toString()));a.push(mg(this));pc(ng(),a)}this.bb=[];og()};
var mg=function(a){return new nc("IP_GH_STEPS_NAVIGATED",a.N+" | "+a.bb.join(", "))},dg=function(a,b){try{for(var c=0,d="";b&&3>c;){d!=b&&(a.bb.push(b),d=b);if("__dismiss__"==b){a.ma();return}pg(a,b);if(!qg(a)){a.ma();return}a.d.finalStep&&(a.Ab=k);eg(a);(b=ag(a.aa))&&++c}if(3<=c)rg(a,"Flow entered an infinite loop. Abandoned.");else{a.l.stop();Aa(a.v);Aa(a.ba);var e=a.Da;if(e){var f=e.title||"",g=e.subTitle||"",j=e.content||"";a.d.modal?(a.q.F(t),a.k.gb.innerHTML=f,a.k.Ka.innerHTML=g,yf(a.k,j),fg(a)):
(a.k.F(t),a.q.gb.innerHTML=f,a.q.Ka.innerHTML=g,yf(a.q,j),a.q.F(k))}else a.k.F(t),a.q.gb.innerHTML="",a.q.Ka.innerHTML="",yf(a.q,""),a.q.F(k);lg(a);gg(a);hg(a,i);ig(a);jg(a,i);for(c=0;c<a.v.length;++c)a.ba.push(af(a.v[c]));for(var l=[S.c.body],c=0;c<a.v.length;++c)for(var p=a.v[c];(p=bf(p))&&!(0<=va(l,p));)if((p.scrollWidth!=p.clientWidth||p.scrollHeight!=p.clientHeight)&&"visible"!=cf(p)){if(!af(p).contains(a.ba[c])){var q=a.v[c],d=p,e=i,n=Hc(q),s=Hc(d),r=Rc(d),lc=n.x-s.x-r.left,z=n.y-s.y-r.top,
M=d.clientHeight-q.offsetHeight,za=d.scrollLeft,cd=d.scrollTop,za=za+Math.min(lc,Math.max(lc-(d.clientWidth-q.offsetWidth),0)),cd=cd+Math.min(z,Math.max(z-M,0)),e=new F(za,cd);d.scrollLeft=e.x;d.scrollTop=e.y}l.push(p);break}var dd=kg(a),Ad;if(Ad=dd){var sb=af(dd),Lf,Mf=Ze(),Qg=Nc(),Rg=uc(Mf,Qg);if(Lf=!Mf.contains(sb)&&Rg.contains(sb)){var yc=Ze(),Sg=sb.left-Math.round(yc.width/2-sb.width/2),Tg=sb.top-Math.round(yc.height/2-sb.height/2),Nf=new F(Math.max(Sg,0),Math.max(Tg,0));(new ff(m,[yc.left,yc.top],
[Nf.x,Nf.y],700,Xe)).play()}Ad=!Lf}if(Ad)a:{var zc=af(dd),Ac=Ze(),Ug=Nc(),Rb,Sb;if(!uc(Ac,Ug).contains(zc)){if(zc.top>=Ac.top+Ac.height)Rb="down",(Sb=a.w.content.scrollDownMsg)||(Sb="scroll down");else if(zc.top+zc.height<=Ac.top)Rb="up",(Sb=a.w.content.scrollUpMsg)||(Sb="scroll up");else break a;a.Ea=new Z(Sb,Rb,m,m,m,a.r);a.Ea.a().className="iph-pointer-scroll-"+Rb;!a.d.modal&&"up"==Rb&&(a.Ea.a().style.left="80%");Tf(a.Ea);a.cb=k}}a.l.start()}}catch(bh){}},pg=function(a,b){var c=ya(a.w.steps,function(a){return b==
a.id});if(c){if(a.d=c,a.Da=a.w.content&&a.w.content.steps&&ya(a.w.content.steps,function(a){return b==a.id}),window.guidedhelp&&window.guidedhelp.onFlowStepSet)window.guidedhelp.onFlowStepSet(b)}else rg(a,"Step ["+b+"] doesn't exist.")};cg.prototype.Zc=function(a){a.Bd==(this.d?this.d.id:m)&&dg(this,a.Ed)};
var eg=function(a){var b=a.d?a.d.id:m;if(b){var c=[],d=A(function(a){var b=a.group;b?(a=this.w.transitionGroups&&ya(this.w.transitionGroups,function(a){return b==a.id}))&&a.transitions&&E(a.transitions,function(a){c.push(a)}):c.push(a)},a);d({group:"__all__"});a.d.transitions&&E(a.d.transitions,d);a=a.aa;Zf(a);a.h.W();a.pa=b;a.jb=c||[];a.Pa=t;W(a.h,a.l,"tick",a.Bb);Yf(a);E(a.jb,function(a){E(a.on,function(a){var b=a.type,c;a:{for(c in Qf)if(b==Qf[c]){c=k;break a}c=t}if(c&&(c=(c=a.selector&&bg(a.selector))&&
0<c.length&&c[0]))switch(b){case "change":W(this.h,c,"change",A(this.R,this,a));break;case "click":H?(a=A(this.R,this,a),c.attachEvent&&(b={},b.element=c,b.type="onclick",b.Hb=a,this.Lb.push(b),c.attachEvent("onclick",a))):W(this.h,c,"click",A(this.R,this,a));break;case "focusIn":case "focusOut":c=new Wf(c);this.Ib.push(c);W(this.h,c,"focusIn"==b?"focusin":"focusout",A(this.R,this,a));break;case "keyPress":W(this.h,c,"keypress",A(this.R,this,a));break;case "mouseOut":W(this.h,c,"mouseout",A(this.R,
this,a));break;case "mouseOver":W(this.h,c,"mouseover",A(this.R,this,a));break;case "submit":W(this.h,c,"submit",A(this.R,this,a));break;case "touchEnd":W(this.h,c,"touchend",A(this.R,this,a))}},this)},a);a.l.start()}},ig=function(a){for(;0<a.Ia.length;){var b=a.Ia.pop();zd(a.h,b.a(),"click",a.eb,k);zd(a.h,b.a(),["mouseover","mouseout"],a.fb,k);hf(b)}},jg=function(a,b){if(a.d.pointers)for(var c=0;c<a.d.pointers.length;++c){var d=a.d.pointers[c];if(!a.d.modal||!a.d.position||!(a.d.position==d.position&&
a.d.direction==d.direction)){var e=t;if(a.d.brackets)for(var f=0;f<a.d.brackets.length;++f){var g=a.d.brackets[f];if(g.elements.join(",")==d.position&&g.direction==d.direction){e=k;break}}g=ya(a.Da.pointers,function(a){return d.id==a.id});a:{var f=a,j=d.position,g=g?g.caption:"",l=d.direction,p=d.leftOffset,q=d.topOffset,n=e,s=b,e=m;if(j&&0<j.length)if(e=bg(j),!e||0==e.length||!$e(e[0])){if(s)break a;rg(f,"Pointer ["+j+"] doesn't exist.")}else if(!s)for(j=0;j<e.length;++j){var s=f.v,r=e[j];0<=va(s,
r)||s.push(r)}g=new Z(g,l,p,q,n,f.r);W(f.h,g.a(),"click",f.eb,k);W(f.h,g.a(),["mouseover","mouseout"],f.fb,k);g.na(e);f.Ia.push(g)}}}},gg=function(a){for(;0<a.Ja.length;)hf(a.Ja.pop())},hg=function(a,b){if(a.d.brackets)for(var c=0;c<a.d.brackets.length;++c){var d=a.d.brackets[c];if(0<d.elements.length){var e=a,f=d.elements.join(", "),g=d.direction,j=d.leftOffset,l=d.topOffset,p=d.lengthOffset,q=b;if((d=bg(f))&&0<d.length&&$e(d[0])){if(f=new kf(g,j,l,p,e.r),f.na(d),e.Ja.push(f),!q)for(f=0;f<d.length;++f)g=
e.v,j=d[f],0<=va(g,j)||g.push(j)}else q||rg(e,"Bracket ["+f+"] doesn't exist.")}}},fg=function(a,b){var c=a.d;if(c.modal&&a.k&&a.k.a()){var d=c.position||"",e=c.direction||"",f=c.leftOffset||0,g=c.topOffset||0,j=0<=c.width?c.width:400,l=m,p=t;if(0==j)a.k.F(t);else{if(d&&"__absolute__"!=d){var q=bg(d);if(!q||0==q.length||!$e(q[0])){if(b)return;rg(a,"Modal ["+d+"] doesn't exist.")}else if(!b)for(var n=0;n<q.length;++n){var s=a.v,r=q[n];0<=va(s,r)||s.push(r)}for(n=0;n<c.pointers.length;++n)if(s=c.pointers[n],
s.position==d&&s.direction==e){l=s;break}for(n=0;n<c.brackets.length;++n)if(s=c.brackets[n],s.elements.join(",")==d&&s.direction==e){p=k;break}a.k.La=q||""}else a.k.La=d||"";a.k.ca(e);a.k.Cb(f);a.k.Db(g);d=a.k;d.a().style.width=Dc(j,k);d.o&&(j=T(d.a()),Lc(d.o,j.width-2,j.height-2));zf(a.k,l);a.k.Eb(p);a:{l=a.k;p=l.Fa;j=l.Ga;d=T(l.a());Y.ANIMATE_POS&&(g=xf(l),f=ob("iph-resize-inner",g),q=e=0,g&&f&&(g=T(g),f=T(f),e=g.width-f.width,q=g.height-f.height),e=new Fa(e,q),d.width-=e.width,d.height-=e.height);
if(""==l.La)e=Ze(),p+=Math.round(e.width/2-d.width/2)+e.left,j+=Math.round(e.height/2-d.height/2)+e.top;else if("__absolute__"!=l.La){e=l.La;ca(e)||(e=[e]);e=df(e);if(!e){l.F(t);break a}f=10+l.V+(l.Ha?4:0)+(l.Ha&&l.V?4:0);"left"==l.e?(p+=e.left+e.width+f,j+=e.top+Math.ceil(e.height/2)-Math.floor(d.height/2)):"right"==l.e?(p+=e.left-d.width-f,j+=e.top+Math.ceil(e.height/2)-Math.floor(d.height/2)):"up"==l.e?(p+=e.left+Math.ceil(e.width/2)-Math.floor(d.width/2),j+=e.top+e.height+f):"down"==l.e&&(p+=
e.left+Math.ceil(e.width/2)-Math.floor(d.width/2),j+=e.top-d.height-f)}!Y.ANIMATE_POS||"none"==l.a().style.display?(Ec(l.a(),p,j),l.o&&(Lc(l.o,d.width-2,d.height-2),Ec(l.o,p,j)),p=l.r,Y.USE_SPOTLIGHT&&(!Y.START_OUTSIDE&&"none"==l.a().style.display)&&(l.r=k),l.F(k),l.r=p):(new Se(l.a(),[p,j],500,Ye)).play()}if(l=Y.USE_SPOTLIGHT)if(l=0<c.brackets.length)if(!(l=!sg))l=!sg.U;l?(lf(),Y.START_OUTSIDE?(c=Jc(),mf(S.c.body,10,rc(c))):mf(a.k.lc(),-5)):0==c.brackets.length&&og()}}},kg=function(a){var b=m;a.d.modal&&
a.d.position?b=a.k.a():0<a.Ia.length?b=a.Ia[0].a():0<a.Ja.length&&(b=a.Ja[0].a());return b},lg=function(a){a.cb&&(hf(a.Ea),a.cb=t)},qg=function(a){if(a.d){var b=a.d.urls;if(!b||0==b.length)b=a.w.defaultUrls;if(b&&0<b.length&&!Boolean(P(S).location.href.match(b.join("|"))))return t}return k},rg=function(a,b){if(qg(a)){var c=b;(c=a.w.content.errorMsg)||(c="Sorry, we can't guide you right now. Please try again later.");if(-1!=c.indexOf("&"))if("document"in v)var d={"&amp;":"&","&lt;":"<","&gt;":">",
"&quot;":'"'},e=document.createElement("div"),c=c.replace(ua,function(a,b){var c=d[a];if(c)return c;if("#"==b.charAt(0)){var l=Number("0"+b.substr(1));isNaN(l)||(c=String.fromCharCode(l))}c||(e.innerHTML=a+" ",c=e.firstChild.nodeValue.slice(0,-1));return d[a]=c});else c=c.replace(/&([^;]+);/g,function(a,b){switch(b){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==b.charAt(0)){var c=Number("0"+b.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return a}});
if(window.guidedhelp&&window.guidedhelp.onError)window.guidedhelp.onError(c);else alert(c)}a.bb.push("__error__("+b+")");a.Fb=k;a.ma();h(Error(b))};var tg=function(){};tg.Uc=function(){return tg.Vc?tg.Vc:tg.Vc=new tg};tg.prototype.ed=0;tg.Uc();var vg=function(a){this.ea=a||N();this.L=ug};C(vg,Ed);vg.prototype.dd=tg.Uc();var ug=m;u=vg.prototype;u.K=m;u.O=t;u.b=m;u.L=m;u.P=m;u.ib=m;u.hb=m;u.mc=t;u.a=function(){return this.b};u.Jb=function(a){return this.b?this.ea.Jb(a,this.b):m};u.X=function(){return this.oa||(this.oa=new xd(this))};u.Pb=function(a){this.P&&this.P!=a&&h(Error("Method not supported"));vg.g.Pb.call(this,a)};u.I=function(){this.b=this.ea.createElement("div")};
u.na=function(a){this.O&&h(Error("Component already rendered"));if(a){this.mc=k;if(!this.ea||this.ea.c!=L(a))this.ea=N(a);this.b=a;this.Ma()}else h(Error("Invalid element to decorate"))};u.Ma=function(){this.O=k;wg(this,function(a){!a.O&&a.a()&&a.Ma()})};u.Na=function(){wg(this,function(a){a.O&&a.Na()});this.oa&&this.oa.W();this.O=t};
u.i=function(){vg.g.i.call(this);this.O&&this.Na();this.oa&&(this.oa.j(),delete this.oa);wg(this,function(a){a.j()});!this.mc&&this.b&&vb(this.b);this.P=this.b=this.hb=this.ib=m};u.lc=function(){return this.b};u.Qc=function(){this.L==m&&(this.L=Ic(this.O?this.b:this.ea.c.body));return this.L};var wg=function(a,b){a.ib&&E(a.ib,b,i)};
vg.prototype.removeChild=function(a,b){if(a){var c=y(a)?a:a.K||(a.K=":"+(a.dd.ed++).toString(36)),d;this.hb&&c?(d=this.hb,d=(c in d?d[c]:i)||m):d=m;a=d;c&&a&&(d=this.hb,c in d&&delete d[c],Ba(this.ib,a),b&&(a.Na(),a.b&&vb(a.b)),c=a,c==m&&h(Error("Unable to set parent component")),c.P=m,vg.g.Pb.call(c,m))}a||h(Error("Child is not in parent component"));return a};var xg=function(a){vg.call(this);this.vd=!!a;this.p={};this.U=m;this.border=-1;this.Ub=t;this.Tb=0};C(xg,vg);
var sg=xg.prototype.ub=m,yg=m,zg=m,lf=function(a){if(Y.USE_SPOTLIGHT&&!sg){if(!yg){var b=O("div","iph-spotlight-parent");Ag(b,0,0,0,0,m,m);wc(b,"position","absolute");var c=S.c.body;c.insertBefore(b,c.childNodes[0]||m);yg=b}a=sg=new xg(a);b=yg;a.O&&h(Error("Component already rendered"));a.b||a.I();b?b.insertBefore(a.b,m):a.ea.c.body.appendChild(a.b);(!a.P||a.P.O)&&a.Ma()}},og=function(){if(yg&&(sg&&!zg)&&(zg=Bg(sg,t,function(){zg=m;Cg();Oc(yg,1)}),Y.START_OUTSIDE)){var a=Jc();mf(S.c.body,10,rc(a))}},
Cg=function(){sg&&!zg&&(Wc(sg),sg=m)},Dg={kd:"iph-spotlight-l",md:"iph-spotlight-t",ld:"iph-spotlight-r",jd:"iph-spotlight-b",Cc:"iph-spotlight-border-l",Ec:"iph-spotlight-border-t",Dc:"iph-spotlight-border-r",Xb:"iph-spotlight-border-b"},Eg="iph-spotlight-anim-begin_"+wd++,Fg="iph-spotlight-anim-end_"+wd++;xg.prototype.i=function(){Gg(this);Ga(Dg,function(a,b){zd(this.X(),this.p[b],"click",this.nc)},this);xg.g.i.call(this)};
xg.prototype.I=function(){xg.g.I.call(this);Ag(this.a(),0,0,0,0,m,m);wc(this.a(),"position","absolute");var a;a=O("div",["iph-spotlight-l","iph-spotlight-bg"]);this.a().appendChild(a);a=O("div",["iph-spotlight-t","iph-spotlight-bg"]);this.a().appendChild(a);a=O("div",["iph-spotlight-r","iph-spotlight-bg"]);this.a().appendChild(a);a=O("div",["iph-spotlight-b","iph-spotlight-bg"]);this.a().appendChild(a);a=O("div",["iph-spotlight-border-t","iph-spotlight-border"]);this.a().appendChild(a);a=O("div",
["iph-spotlight-border-l","iph-spotlight-border"]);this.a().appendChild(a);a=O("div",["iph-spotlight-border-b","iph-spotlight-border"]);this.a().appendChild(a);a=O("div",["iph-spotlight-border-r","iph-spotlight-border"]);this.a().appendChild(a);Ga(Dg,function(a,c){this.p[c]=this.Jb(a);U(this.p[c],t);W(this.X(),this.p[c],"click",this.nc)},this)};xg.prototype.Ma=function(){xg.g.Ma.call(this);W(this.X(),P(S),"resize",this.cc);this.cc()};
xg.prototype.Na=function(){xg.g.Na.call(this);zd(this.X(),P(S),"resize",this.cc);Lc(yg,0,0)};
var Hg=function(a,b){var c;c===i&&(c=k);c||(a.U=m,Gg(a));Ga(a.p,function(a,b){U(this.p[b],c)},a);if(0>a.border){var d=a.p.Xb,d=R(d,"borderBottomWidth")||xc(d,"borderBottomWidth")||d.style&&d.style.borderBottomWidth;switch(d){case "thin":d="2px";break;case "medium":d="4px";break;case "thick":d="6px"}d=/(\-*\d*)(\D*)/.exec(d);a.border=parseFloat(d[1])||4}a.U=b;var b=b.u(),d=b.width+b.left,e=b.height+b.top,f=a.border+0;Ag(a.p.kd,0,0,m,0,b.left,m);Ag(a.p.md,b.left,0,m,m,b.width,b.top);Ag(a.p.ld,d,0,0,
0,m,m);Ag(a.p.jd,b.left,e,m,0,b.width,m);Ec(a.p.Cc,b.left-a.border,b.top-a.border);Ag(a.p.Cc,m,m,m,m,f,b.height+2*a.border);Ec(a.p.Ec,b.left-a.border,b.top-a.border);Ag(a.p.Ec,m,m,m,m,b.width+2*a.border,f);Ec(a.p.Dc,d-f,b.top-a.border);Ag(a.p.Dc,m,m,m,m,f,b.height+2*a.border);Ec(a.p.Xb,b.left-a.border,e-f);Ag(a.p.Xb,m,m,m,m,b.width+2*a.border,f)},Ag=function(a,b,c,d,e,f,g){a&&(b!=m&&wc(a,"left",b?b+"px":"0"),c!=m&&wc(a,"top",c?c+"px":"0"),d!=m&&wc(a,"right",d?d+"px":"0"),e!=m&&wc(a,"bottom",e?e+"px":
"0"),f!=m&&(da(f)&&0>f&&(f=0),a.style.width=Dc(f,k)),g!=m&&(da(g)&&0>g&&(g=0),Kc(a,g)))},Ig=function(a,b,c){if(!b)return m;var c=c||0,d=Hc(b),b=T(b);return 0==d.x&&0==d.y&&0==b.width&&0==b.height?new Q(0,0,0,0):new Q(d.x-c-a.border,d.y-c-a.border,b.width+2*c+a.border,b.height+2*c+a.border)},Gg=function(a){a.H&&(1==a.H.G&&a.H.stop(),a.H&&(sd(a.H),a.H=m),a.ub=m)},Bg=function(a,b,c){var d;Ga(a.p,function(a){var c=1,g=kb(a);0<=va(g,"iph-spotlight-bg")&&(c=0.4);d=new Ue(a,b?0:c,b?c:0,500);d.play()});c&&
nd(d,"end",c);return d},mf=function(a,b,c){var d=sg;d.Ub=k;Gg(d);d.Ub=t;d.ub=a;d.Tb=b||0;d.Gc=c;a=d.Gc||Ig(d,d.ub,d.Tb);d.U?(d.H=new Jg([d.U.left,d.U.top,d.U.width,d.U.height],[a.left,a.top,a.width,a.height],500,Ye),W(d.X(),d.H,["begin","animate","end"],d.sd,t,d),W(d.X(),d.H,"begin",d.Ic),W(d.X(),d.H,"end",d.Hc),d.H.play(t)):(Hg(d,a),d.Ic(),d.Hc(),Bg(d,k))};u=xg.prototype;
u.sd=function(a){Hg(this,new Q(Math.round(a.coords[0]),Math.round(a.coords[1]),Math.round(a.coords[2]),Math.round(a.coords[3])));a=this.Gc||Ig(this,this.ub,this.Tb);this.H.setEndPoint([a.left,a.top,a.width,a.height])};u.Ic=function(){this.dispatchEvent(Eg)};u.Hc=function(){this.Ub||this.dispatchEvent(Fg)};u.nc=function(a){this.dispatchEvent(a);this.vd&&Cg()};
u.cc=function(){U(yg,t);U(this.a(),t);var a=S.c,b=rb((a?a.parentWindow||a.defaultView:window)||window||window),c=Math.max(b.width,Math.max(a.body.scrollWidth,a.documentElement.scrollWidth)),a=Math.max(b.height,Math.max(a.body.scrollHeight,a.documentElement.scrollHeight));U(yg,k);Lc(yg,c,a);U(this.a(),k);Lc(this.a(),c,a)};var Jg=function(a,b,c,d){Ne.call(this,a,b,c,d)};C(Jg,Ne);
Jg.prototype.setEndPoint=function(a){(!x(a)||a.length!=this.ha.length)&&h(Error("New target array must match size of origin array."));this.Oc=a};B("help.guide.util.toJson",function(a){return Jd(a)});B("help.guide.util.fromJson",function(a){return Fd(a)});var Kg=m,Cd="en",Lg="v3",Mg=k,S=new mb,Y={},ng=function(){return Kg+"/api/metrics?hl="+Cd};B("help.guide.createDivConsole",function(){return m});B("help.guide.setUseLocalDiskResources",function(a){Mg=a});
B("help.guide.init",function(a,b,c,d){Kg=a;Cd=b||Cd;Lg=c||Lg;if("v2"==Lg||"maps"==Lg||"orkut"==Lg)Lg="v3";S=N(d||window.top);if(!window.guidedhelp||!window.guidedhelp.stylesLoaded)a=new Sd,Mg?a.append("//ssl.gstatic.com/inproduct_help/guide/guidedhelp"):(b=new Gb(Kg),Kb(b,"/support/gh/style/guidedhelp"),a.append(b.toString())),0<Lg.length&&(a.append("_"),a.append(Lg)),a.append(".css"),a=a.toString(),c=m,b=nb(S.c,"head",i,i)[0],b||(c=nb(S.c,"body",i,i)[0],b=S.I("head"),c.parentNode.insertBefore(b,
c)),c=S.I("link"),c.setAttribute("type","text/css"),c.setAttribute("rel","stylesheet"),c.setAttribute("href",a),S.appendChild(b,c),window.guidedhelp=window.guidedhelp||{},window.guidedhelp.stylesLoaded=k;""==xe&&(a=window.location.hostname,-1==a.indexOf(":")&&-1==a.indexOf("/")&&(b=a.split("."),3==b.length?xe="."+b[1]+"."+b[2]:(b=a.indexOf(".google."),-1<b&&(xe=a.substr(b)))))});B("help.guide.optionallyResume",function(){var a=Ce();if(a){var b=De();Ee();Ng(a,b,t)}});
var $=m,Og=new xd,Pg=function(){$!=m&&($.j(),$=m);Og.W()};B("help.guide.reset",Pg);var Vg=function(){$!=m&&$.ma()};B("help.guide.dismissFlow",Vg);B("help.guide.getCurrentStepJson",function(){return $==m?m:Jd($.d)});B("help.guide.getCurrentStepContentJson",function(){return $==m?m:Jd($.Da)});
var Ng=function(a,b,c,d){var e;e=Kg+"/api/answer/"+a+"/guidedhelp?hl="+Cd;if(window.guidedhelp&&window.guidedhelp.onFlowLoadStart)window.guidedhelp.onFlowLoadStart(a,e);e=new gc(e);e.Xa=6E4;e.send({},A(Wg,m,a,b,c==m?k:c,d),Xg)};B("help.guide.loadFlow",Ng);B("help.guide.startFlow",function(a,b,c,d){Kf(a);Yg(a,b,c,d)});B("help.guide.goToStep",function(a){$!=m&&dg($,a)});
var Yg=function(a,b,c,d){Y=a.globals||{};Y.USE_SPOTLIGHT&&lf();Vg();var e=O("div","g-help-css-done");S.c.body.appendChild(e);var f=function(){"none"===R(e,"display")||"none"===xc(e,"display")?(vb(e),Pg(),$=new cg(0,a,b||m,m,d,Lg),W(Og,$,"newflowlink",Zg),W(Og,$,"dismiss",$g),dg($,c||"__start__")):setTimeout(f,50)};f()},Wg=function(a,b,c,d,e){e=e.flow;Kf(e);if(window.guidedhelp&&window.guidedhelp.onFlowLoadSuccess)window.guidedhelp.onFlowLoadSuccess(a,e);Yg(e,a,b,d);c&&ah(a)},ah=function(a){var b=
[];b.push(new nc("IP_GH_LOADED",String(a)));pc(ng(),b)};B("help.guide.logLoadedFlow",ah);var Xg=function(){if(window.guidedhelp&&window.guidedhelp.onFlowLoadFailure)window.guidedhelp.onFlowLoadFailure()},Zg=function(a){Ng(Number(a.Wd))},$g=function(){Ee();Pg()};B("help.guide.getToolsUrl",function(){var a=new Gb(Kg);Kb(a,"/support/api/guidedhelptools");return a.toString()});B("help.guide.checkXdRpc",function(a){a:switch(a.target.status){case 200:case 304:a=k;break a;default:a=t}return a?k:t});
B("help.guide.logInfo",function(){});
B("help.guide.xdRpcSend",function(a,b,c,d){var e=new Nd;b&&ld(e,"complete",b);ld(e,"ready",e.reset);var b=e.xb=document.createElement("iframe"),f=Qd++;b.id="xdrq-"+f;b.style.position="absolute";b.style.top="-5000px";b.style.left="-5000px";document.body.appendChild(b);var g=[];g.push(Od("xdpe:request-id",f));f=Pd();g.push(Od("xdpe:dummy-uri",f));if(d)for(var j in d)g.push(Od("xdp:"+j,d[j]));a='<body><form method="'+("GET"==c?"GET":"POST")+'" action="'+a+'">'+g.join("")+"</form></body>";c=b.contentDocument||
b.contentWindow.document;c.open();c.write(a);c.close();c.forms[0].submit();c=m;e.Md=ld(b,"load",function(){this.Od=k},t,e);e.kc=0;var l=window.setInterval(A(function(){a:{var a=l,b=this.xb.contentWindow,c=b.frames.length,d=m,e;if(e=0<c){c=d=b.frames[c-1];try{e=1==Rd(c).indexOf("xdrp-info")}catch(f){e=t}}if(e){d=Rd(d).substring(1);d=new Mb(d);e=[];for(var c=Number(d.get("n")),g=0;g<c;g++){var j=b.frames[g];if(!j||!j.location||!j.location.href)break a;j=Rd(j);e.push(j.substring(j.indexOf("chunk")+5+
1))}window.clearInterval(a);a=e.join("");H||(a=decodeURIComponent(a));this.status=Number(d.get("status"));this.responseText=a;this.Pd="true"==d.get("isDataJson");Gd(d.get("headers"));this.dispatchEvent("ready");this.dispatchEvent("complete")}else this.Od&&(this.kc+=50,500<this.kc&&(window.clearInterval(a),this.status=500,this.responseText="response timed out",this.dispatchEvent("ready"),this.dispatchEvent("error"),this.dispatchEvent("complete")))}},e),50)});
B("help.guide.jsonp",function(a){a=new gc(a);a.Xa=6E4;return a});B("help.guide.getResponseJson",function(a){return a.target.Pd?Gd(a.target.responseText):i});B("help.guide.getLocale",function(){return Cd});
var bg=function(a){var b=-1,c=a.match(/IFRAME\[(\d+|['"]\w+['"])\] /);c&&(a=a.replace(/IFRAME\[(\d+|['"]\w+['"])\] /g,""),b=c[1],b=b.replace(/["']/g,""));var d=S.c;b&&-1!=b&&((c=P(S).frames[b])?d=c.document:(c=nb(document,"iframe",i,i),E(c,function(a){var c=a.getAttribute("id"),g=a.getAttribute("name"),j=a.getAttribute("guidedhelpid");if(c==b||g==b||j==b)d=a.contentDocument||a.contentWindow.document})));return qe(a,d)};B("help.guide.query",bg);window.guidedhelp||(window.guidedhelp={});window.guidedhelp.loaded=k;if(window.guidedhelp.onLoad)window.guidedhelp.onLoad();})();
