var outbrain_dual_version="6.5.1.1",outbrain_dual_template_object=typeof outbrain_dual_template_object=="function"?outbrain_dual_template_object:function(o){var k=this;outbrain_dual_template_object.baseConstructor.call(this,o);this.imagesPreload=function(){};this.positionFirstLine=this.positionSecondLine=false;this.positionRec=this.positionDynSecondLine=true;this.positionsStars=false;outbrain_template_manager.isAdMarking=true;this.adFieldsetId="outbrain_dual_ad_fs";this.adFieldsetClass="outbrain_dual_ad_class";
this.adUlElementId="outbrain_dual_ad_ul";this.adUlClassDual="outbrain_dual_ad_ul_class";this.regUlClassDual="outbrain_dual_reg_ul_class";this.adWhatsThisId="outbrain_dual_ad_whats";this.dividerId="outbrain_dual_divider";this.adWhatsThisClass="outbrain_dual_ad_whats_class";this.adWhatsThisHrfClass="outbrain_dual_ad_whats_A_class";this.buildDomDivider=function(){var a=[];a.push('<p id="'+this.dividerId+'_$INDEX_$TEMPLATE_NAME" style="height:5px;margin:0px;padding:0px;display:none"></p>');return a.join("")};
this.buildDomAdRecommendation=function(a){var c=outbrain_browsers.ie&&(outbrain_browsers.ie8Doc8||outbrain_browsers.ie9Doc8Plus)?" outbrain_dual_ad_ul_ie8_class":"",b=[];b.push('<fieldset style="display:none;$FIELDSET_STYLE" id="'+this.adFieldsetId+'_$INDEX_$TEMPLATE_NAME" class="$FIELDSET_CLASS '+this.adFieldsetClass+'" >');b.push('    <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');b.push('  \t<ul id="'+this.adUlElementId+'_$INDEX_$TEMPLATE_NAME" class="'+this.adUlClassDual+' $RECOMMENDATIONS_UL_CLASS" '+
c+">");b.push("  \t</ul>");outbrain_whatIs.isBrandingCustom(a)?b.push('    <div style="clear:both;" id="'+this.adWhatsThisId+'_$INDEX_$TEMPLATE_NAME" class="'+this.adWhatsThisClass+' " ></div>'):b.push(outbrain_whatIs.buildLogicDomWhatIs(a));b.push("</fieldset>");return b.join("")};this.buildDomRecommendations=function(a){var c=outbrain_settings.get(a,"adMarkingOnTop",true),b=[];if(c==true){b.push(this.buildDomAdRecommendation(a,"outbrain_dual_ul_ad_top"));b.push(this.buildDomDivider(a))}b.push('<fieldset style="display:none;$FIELDSET_STYLE" id="$FIELDSET_ID_$INDEX_$TEMPLATE_NAME" class="$FIELDSET_CLASS" >');
b.push('      <div id="$RECOMMENDATIONS_WAIT_ID_outer_$INDEX" class="$RECOMMENDATIONS_WAIT_CLASS_outer" style="display:none;"><div class="$RECOMMENDATIONS_WAIT_CLASS_inner">');b.push('               <p><img style="border:0px !important"/></p>');b.push("       </div></div>");b.push('       <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');b.push('  \t<ul id="$RECOMMENDATIONS_UL_ID_$INDEX_$TEMPLATE_NAME" class="'+this.regUlClassDual+' $RECOMMENDATIONS_UL_CLASS" style="display:block">');b.push("  \t</ul>");
b.push("</fieldset>");b.push('<table id="$RECOMMENDATIONS_STATUS_ID_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_STATUS_TABLE_CLASS" style="display:none;"><tr><td>');b.push('\t<div id="$RECOMMENDATIONS_PC_LEGEND_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_PC_LEGENED_CLS" style="display:none;"></div>');b.push("</td><td>");b.push('\t<div id="$RECOMMENDATIONS_MORE_DIV_ID_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_MORE_LINK_DIV_CLASS" style="display:none;"></div>');b.push("</td></tr></table>");
if(c!=true){b.push(this.buildDomDivider(a));b.push(this.buildDomAdRecommendation(a,"outbrain_dual_ul_ad_bottom"))}return b.join("")};this.showRecommendations=function(a,c){var b=c.recTitle;c=c.jsonObj;if(!this.positionRec)return false;if(this.recommendationsShowBefore(a))this.recommendationsLegendUpdate(a,b);else{var e=this.getElementWithFullName(this.constants.recommendationsUlId,a),g=this.getElementWithFullName(this.adUlElementId,a);this.recommendationsLegendUpdate(a,b);var f=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_REGULAR_ONLY,
c.response.documents.doc,null,null);b=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_AD_ONLY,c.response.documents.doc,null,null);var d=outbrain_settings.get(a,"filterRegRecs",false),i=outbrain_template_manager.isAllSameSource(c.response.documents);d=typeof d=="boolean"&&d==true?0:f.length;var j=outbrain_settings.getNum(a,"defaultRecNumber"),l=j<=d?j:d;j=d-l;var m=b.length;if(d>0)OB_widgetObjArray[a].SecLineOn=false;var n=e&&typeof e.opened=="boolean"&&e.opened==
true;if(typeof OB_user_mode=="number"&&OB_user_mode==1){if(n)l=d;this.clearRecommendations(a,j)}for(var h=0;h<d;h++)this.renderOneRecommendation(a,e,f[h],h,i,h<l?true:false);for(e=0;e<m;e++){f=this.getCampType(a,c.response.documents);this.renderTitleAdRecommendation(a,g,e,c,f);this.renderOneRecommendation(a,g,b[e],h+e,i,true)}this.showHideElementByIdName(this.constants.fieldsetId,a,d>0);this.showHideElementByIdName(this.dividerId,a,m>0&&d>0);this.setAdBoxPlace(a,m);this.checkIfMoreRecs(a,j,n);this.showHideRecsElements(a,
c);this.enableBlogExternalElements(a);this.checkBottomTableWrapper(a)}};this.setAdBoxPlace=function(a,c){var b=this.getElementWithFullName(this.adFieldsetId,a);if(b&&b.style.display=="none"){b=outbrain_settings.get(a,"hookId",null);typeof b=="string"&&b.length>0&&c>0?this.hookAdsBox(b,a):this.showHideElementByIdName(this.adFieldsetId,a,c>0)}};this.recommendationsShowBefore=function(a){var c=false;c=this.getElementWithFullName(this.constants.fieldsetId,a);var b=this.getElementWithFullName(this.adFieldsetId,
a);c=c?c.style.display!="none"||b.style.display!="none":false;if(c==true&&typeof OB_user_mode=="number"&&OB_user_mode==1){this.removeWaitClock(a);c=false}return c};this.showHideRecsElements=function(a,c){this.setAdLegend(a,c);if(c=this.getElementWithFullName(this.constants.rateStatusInfoTableId,a))c.style.display="none";if(c=this.getElementWithFullName(this.constants.rateStatusInfoTdId,a))c.style.display="none";if(c=this.getElementWithFullName(this.constants.fieldsetId,a))OB_widgetObjArray[a].hasRecommendations=
true};this.renderTitleAdRecommendation=function(a,c,b,e,g){c=this.getpcName(a,e.response.documents);b="";b=g!=null&&g==2&&typeof outbrain_language_manager.getPiLegendText=="function"?outbrain_language_manager.getPiLegendText(a,c)+":":outbrain_language_manager.getPcLegendText(a,c)+":";this.adsLegendUpdate(a,b);this.adsWhatsThisUpdate(a)};this.adsWhatsThisUpdate=function(a){var c=outbrain_language_manager.whatsThis(a),b='<a class="'+this.adWhatsThisHrfClass+'" href="javascript:void(0)" onClick="javascript:'+
this.callForToolTip(a,"this",false)+'" >[$AD_TEXT]</a>';b=b.replace(/\$AD_TEXT/g,c);(a=this.getElementWithFullName(this.adWhatsThisId,a))&&k.dom.setInnerHTML(a,b)};this.showHideElementByIdName=function(a,c,b){if(a=this.getElementWithFullName(a,c))a.style.display=b?"block":"none"};this.adsLegendUpdate=function(a,c){if(a=this.getElementWithFullName(this.adFieldsetId,a))if((a=a.getElementsByTagName("legend")[0])&&a.innerHTML!=c){a.className=this.constants.recommendationsLegendClass;k.dom.setInnerHTML(a,
c)}};this.createLinkOfPC=function(){return""};this.isSonOf=function(a,c){if(a&&a.childNodes.length>0&&c){a=a.childNodes;for(var b=0;b<a.length;b++)if(a[b].id==c.id)return c}return null};this.hookAdsBox=function(a,c){var b=this.adFieldsetId+"_"+c+"_"+this.templateName,e=this.getElementWithFullName(this.constants.voterDivName,c);try{new outbrain_timeout(function(){if(document.getElementById(a+"_"+c))return true;return false},function(){var f=document.getElementById(a+"_"+c);if(f){var d=document.getElementById(b);
if(d){d.className+=outbrain_language_manager.isRtl(c)==true?" div-wrapper-right":" div-wrapper";k.cleanHookContainer(f,d);var i=d.cloneNode(true);f.appendChild(i);i.style.display="block";f.style.display="block";e.removeChild(d)}}},null,function(){var f=document.getElementById(b);if(f)f.style.display="block"},1E3,15,true)}catch(g){}};this.cleanHookContainer=function(a,c){try{if(this.isSonOf(a,c)!==null)a.innerHTML=""}catch(b){}};this.resetTemplate=function(a){if(typeof OB_user_mode=="number"&&OB_user_mode==
1){var c=this.getElementWithFullName(this.adFieldsetId,a);if(c)c.style.display="none";if(c=this.getElementWithFullName(this.constants.fieldsetId,a))c.style.display="none";if(c=this.getElementWithFullName(this.constants.recommendationsPcLegendId,a))c.style.display="none"}};this.clearRecommendations=function(a,c){var b=this.getElementWithFullName(this.adUlElementId,a);if(b!=null)b.innerHTML="";b=this.getElementWithFullName(this.constants.recommendationsUlId,a);if(b!=null)b.innerHTML="";a=this.getElementWithFullName(this.constants.recommendationsMoreDivId,
a);if(a!=null&&c<1)a.innerHTML=""};this.showBalloon=false};outbrain_dual_template_object.prototype=outbrain_template_object;outbrain_dual_template_object.prototype.constructor=outbrain_dual_template_object;outbrain_dual_template_object.baseConstructor=outbrain_template_object;outbrain_template_manager.addTemplate({dual:outbrain_dual_template_object});
